### ISSUE TITLE
Unexpected Blocking of GOOD iOS devices 

### ISSUE THREAD

**Issue by s2terminal** [mitchellkrogza/apache-ultimate-bad-bot-blocker#101]
I think bad user agent list is unexpectedly blocking GOOD iOS devices.

Please remove that rule or add iOS user agent to whitelist.

## Example
On my iPad, user agent of [iOS ‎Google App](https://itunes.apple.com/us/app/google/id284815942?mt=8) is below.
```
Mozilla/5.0 (iPad; CPU OS 11_3_1 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) GSA/56.0.208290612 Mobile/15E302 Safari/604.1
```
including `GSA`.

### Expected behavior
Allowed.

### Actual behavior
Blocked by [this rule](https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/Apache_2.2/custom.d/globalblacklist.conf#L746).

```
BrowserMatchNoCase "^(.*?)(\bGsa\b)(.*)$" bad_bot
```

**Comment by s2terminal** [comment]
@davcpas1234 Thank you very much for your quick response!

**Comment by mitchellkrogza** [comment]
Merged wait for build to complete +- 5 minutes and then update
