### ISSUE TITLE
CentOS 7

### ISSUE THREAD

**Issue by srmobile** [mitchellkrogza/apache-ultimate-bad-bot-blocker#11]
Is there a guide or easy way to get this to work with CentOS 7?

**Comment by mitchellkrogza** [comment]
I only recently loaded CentOS7 in a virtual machine to try this out. Wasn't too impressed with CentOS7 vs 6.8 but I am busy looking into this just haven't had much time on my hands. 

Check updated paths provided by @stevetoza in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/78a8c521cc184786d3a391e75437fda47acc63fc and see if that helps. Let me know otherwise I will dig into CentOS7 and figure it out for you.

**Comment by mitchellkrogza** [comment]
Added in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/16d601d36ff79426d3dc409730be929020b1e9c4

**Comment by srmobile** [comment]
Much appreciated, I will give it a try this weekend!

**Comment by mitchellkrogza** [comment]
No problem, shout if you have any issues. I just did this and tested it this morning on a fresh install of CentOS7 and it worked like a charm.

**Comment by srmobile** [comment]
Okay I've included the new .conf file in my virtualhost, I dont have any errors on service reload or restart but when I run some tests like "curl -I http://yourdomain.com -e http://100dollars-seo.com" i'm getting response 200. 

I have some existing blocking rules in my .htaccess for my website, I will try removing them all tomorrow and see if it makes a difference but wanted to check in.

**Comment by mitchellkrogza** [comment]
@srmobile may seem like a silly question but did you replace http://yourdomain.com in the curl command with your real domain name?

**Comment by srmobile** [comment]
Hi Mitchell,

Yes I was replacing with my site. I am also running virtualmin so I dont know if it would be interfering, I do know that the rules  for my .htaccess works. Maybe I have it loaded in the wrong place?

Thanks for your help!

SR

Here is the port 80 version of my httpd.conf, the 443 version is essentially the same:

<VirtualHost *:80>
SuexecUserGroup "#500" "#500"
ServerName my_website.ca
ServerAlias www.my_website.ca
ServerAlias webmail.my_website.ca
ServerAlias admin.my_website.ca
DocumentRoot /home/my_website/public_html
ErrorLog /var/log/virtualmin/my_website.ca_error_log
CustomLog /var/log/virtualmin/my_website.ca_access_log combined
ScriptAlias /cgi-bin/ /home/my_website/cgi-bin/
ScriptAlias /awstats/ /home/my_website/cgi-bin/
DirectoryIndex index.html index.htm index.php index.php4 index.php5
<Directory /home/my_website/public_html>
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
Include /etc/httpd/custom.d/globalblacklist.conf
AddType application/x-httpd-php .php
AddHandler fcgid-script .php
AddHandler fcgid-script .php7.0
FCGIWrapper /home/my_website/fcgi-bin/php7.0.fcgi .php
FCGIWrapper /home/my_website/fcgi-bin/php7.0.fcgi .php7.0
</Directory>
<Directory /home/my_website/cgi-bin>
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
</Directory>
RewriteEngine on
RewriteCond %{HTTP_HOST} =webmail.my_website.ca
RewriteRule ^(.*) https://my_website.ca:20000/ [R]
RewriteCond %{HTTP_HOST} =admin.my_website.ca
RewriteRule ^(.*) https://my_website.ca:10000/ [R]
RemoveHandler .php
RemoveHandler .php7.0
php_admin_value engine Off
FcgidMaxRequestLen 1073741824
Alias /dav /home/my_website/public_html
<Location /dav>
DAV on
AuthType Basic
AuthName "my_website.ca"
AuthUserFile /home/my_website/etc/dav.digest.passwd
Require valid-user
ForceType text/plain
Satisfy All
RemoveHandler .php
RemoveHandler .php5
RewriteEngine off
</Location>
IPCCommTimeout 3601
<Files awstats.pl>
AuthName "my_website.ca statistics"
AuthType Basic
AuthUserFile /home/my_website/.awstats-htpasswd
require valid-user
</Files>
</VirtualHost> <

**Comment by mitchellkrogza** [comment]
I think your problem is the way you have your vhosts configured. The order of your rules is important, you are first telling apache to:

```
allow from all
AllowOverride All 
Require all granted

```
and then telling Apache to obey your blacklist with

`Include /etc/httpd/custom.d/globalblacklist.conf`

But the rule order overrides the blacklist.

So your order should be more like:

```
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Include /etc/httpd/custom.d/globalblacklist.conf
allow from all
AllowOverride All 
Require all granted

```
Here is an example of how your vhosts should be configured on Apache. This example is for an SSL sites with a port 80 redirect running a wordpress site.

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	DocumentRoot /var/www/html/mydomain
	ServerName mydomain.com
	ServerAlias www.mydomain.com
	ErrorLog ${APACHE_LOG_DIR}/mydomain-error.log
	CustomLog ${APACHE_LOG_DIR}/mydomain-access.log
<Directory "/var/www/html/mydomain/">
	Options +Includes
	Options +FollowSymLinks -Indexes
	Include /etc/apache2/custom.d/globalblacklist.conf
# BEGIN WordPress
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /
	RewriteRule ^index\.php$ - [L]
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule . /index.php [L]
## END WordPress ##
</Directory>
<Directory "/var/www/html/mydomain/">
    AllowOverride All
    Options +Indexes
    Require all granted
    Allow from all
</Directory>
	SSLCertificateFile /etc/letsencrypt/live/mydomain.com/cert.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateChainFile /etc/letsencrypt/live/mydomain.com/chain.pem
</VirtualHost>
</IfModule>
<VirtualHost *:80>
	ServerName mydomain.com
	ServerAlias www.mydomain.com
	ErrorLog ${APACHE_LOG_DIR}/mydomain-error.log
	CustomLog ${APACHE_LOG_DIR}/mydomain-access.log
	RewriteEngine On
 	# Redirect all HTTP traffic to HTTPS.
	RewriteCond %{HTTPS} !=on
	RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>




```

**Comment by srmobile** [comment]
Hi Mitchell

Okay I got it working with your assistance, but 2 things to note:

1. I had rules in my .htaccess that were taking priority over the rules loaded by globalblacklist.conf
2. I was using one of your examples as a copy paste and the domain isn't there anymore (zyzzcentral.ru)

My website has picked up speed, no doubt because of all my complex rules in .htaccess were slowing it down.

1 more quick question: If I want to maintain my own blacklist (competitors) what would be the best way to do this since it appears that the globalblacklist.conf gets updated regularly?

Thanks!

SR

**Comment by mitchellkrogza** [comment]
Yes running .htaccess rules is just duplicating and slowing your site down, .htaccess in general is a big cause for the slow down of sites whereas my blocker sits in Apache's memory all the time and is immediate to deal with bad bots and refererrers. You must remember how .htaccess works, .htaccess does not stay resident in memory, every single IP and request that hits your site will constantly speak to .htaccess read it's rules and then decide what to do. I do not use .htaccess on any sites unless it's a simple file to keep someone out of a private folder. Rewrite rules and all that stuff must be put into your vhost config file and not into .htaccess

I constantly remove domains that no longer exist .... I still need to fix a few pages that reference using zyzzcentral.ru as a test ..... it's no longer in existence and no longer blocked as the domain no longer exists.

```
nslookup http://zyzzcentral.ru/
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find http://zyzzcentral.ru/: NXDOMAIN
```

**Comment by mitchellkrogza** [comment]
Glad you got it working !!!

**Comment by srmobile** [comment]
Quick one for you: I'm using Alexa and when I run a scan it is returning 403 -  Alexa is telling me the bot name is "Alexabot" but its not on the list. Any hints?

Thanks!

**Comment by mitchellkrogza** [comment]
It's called Alexibot and it is listed. I use it to keep SEO companies and competitors from accumulating data off my sites.

**Comment by Freeforyall** [comment]
Hello Mitchell,

I am using Ubuntu Linux 18.04.1 with Apache version 2.4.29 and Webmin/Virtualmin. If I go into Services, Configure SSL Website, this is my configuration:


```
SuexecUserGroup "#1001" "#1001"
ServerName mywebsite.com
ServerAlias www.mywebsite.com
DocumentRoot /home/mywebsite/public_html
ErrorLog /var/log/virtualmin/mywebsite.com_error_log
CustomLog /var/log/virtualmin/mywebsite.com_access_log combined
ScriptAlias /cgi-bin/ /home/mywebsite/cgi-bin/
DirectoryIndex index.html index.htm index.php index.php4 index.php5
<Directory /home/mywebsite/public_html>
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
AddType application/x-httpd-php .php
AddHandler fcgid-script .php
AddHandler fcgid-script .php7.2
FCGIWrapper /home/mywebsite/fcgi-bin/php7.2.fcgi .php
FCGIWrapper /home/mywebsite/fcgi-bin/php7.2.fcgi .php7.2
</Directory>
<Directory /home/mywebsite/cgi-bin>
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
</Directory>
RewriteEngine on
RewriteCond %{HTTP_HOST} =admin.mywebsite.com
RewriteRule ^(.*) https://mywebsite.com:10000/ [R]
RemoveHandler .php
RemoveHandler .php7.2
#php_admin_value engine Off
FcgidMaxRequestLen 1073741824
SSLEngine on
SSLCertificateFile /home/mywebsite/ssl.cert
SSLCertificateKeyFile /home/mywebsite/ssl.key
SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCACertificateFile /home/mywebsite/ssl.ca
```


But if I change it to what you suggested to srmobile:

```
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Include /etc/apache2/custom.d/globalblacklist.conf
allow from all
AllowOverride All 
Require all granted
```

This line: 

`Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch`

throws the following error when I run apache2ctl configtest:

`Invalid command 'Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch'`

Can you please help me figure out what I'm doing wrong?

Thank you!
