### ISSUE TITLE
why is my Android blocked

### ISSUE THREAD

**Issue by uleodolter** [mitchellkrogza/apache-ultimate-bad-bot-blocker#113]
I cant figure out why my mobile phone is blocked, firefox and chrome, tried from different ip's too.

"Mozilla/5.0 (Android 8.1.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0"
"Mozilla/5.0 (Linux; Android 8.1.0; Moto G (5) Plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"

Any ideas?

**Comment by mitchellkrogza** [comment]
Please can you post the log excerpts for me

**Comment by uleodolter** [comment]
Maybe i don't understand the overall logic,  what is the default action  if a browser is not whitelisted and not blacklisted and none of the rules matches ?

simulation access using curl works for good_bot entries like googlebot, but not for `\bMozilla` which is not listed in good or bad rules.

**Comment by mitchellkrogza** [comment]
Default action for anything is ALLOW the only way to trace what's blocking you is to see your log lines

**Comment by uleodolter** [comment]
```
46.125.250.37 - - [12/Feb/2019:10:12:41 +0100] "GET /robots.txt HTTP/1.1" 403 26 "-" "Mozilla/5.0 (Android 8.1.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0"
```

**Comment by mitchellkrogza** [comment]
Because of a `403` error it's more likely a permissions problem on your system. The blocker does not block access to robots.txt nor does it block me using your user-agent string as below test shows.

`curl -A "Mozilla/5.0 (Android 8.1.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0" https://mysite/robots.txt`

```User-agent: * 
Disallow:```

**Comment by mitchellkrogza** [comment]
I also tested the first two user-agent strings you posted and they are not blocked either.

```
curl -A "Mozilla/5.0 (Android 8.1.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0" https://mysite/robots.txt
User-agent: * 
Disallow:
```

and

```
curl -A "Mozilla/5.0 (Linux; Android 8.1.0; Moto G (5) Plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36" https://mysite/robots.txt
User-agent: * 
```

and to confirm the blocker is active

```
curl -A "Xenu Link Sleuth/1.3.8" https://mysite/robots.txt
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /robots.txt
on this server.<br />
</p>
</body></html>
```

**Comment by uleodolter** [comment]
i have the following apache rule:

```
<Location "/robots.txt">
    AuthMerging And
    Include custom.d/globalblacklist.conf
    ErrorDocument 403 /error/robots.txt
</Location>
```

please try:

```
curl -A "googlebot"  http://digital.obvsg.at/robots.txt
curl -A "Mozilla"  http://digital.obvsg.at/robots.txt
```

**Comment by mitchellkrogza** [comment]
Something wrong with the way you have configured the blocker.

Test 1: (shows sitemap as below ... truncated)
```
curl -A "googlebot"  http://digital.obvsg.at/robots.txt
Sitemap: https://digital.obvsg.at/sitemap.xml
User-agent: *
Disallow: /download/
Disallow: /image/
```

Test 2: (with declared bad bot) > Allowed but shown a different robots.txt than above :thinking: 
```
curl -A "Ahrefs"  http://digital.obvsg.at/robots.txt
User-agent: *
Disallow: /
```
Test 3: (with previous user agent you gave) > Allowed but shown a different robots.txt than above :thinking: 
```
curl -A "Mozilla/5.0 (Android 8.1.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0"  http://digital.obvsg.at/robots.txt
User-agent: *
Disallow: /
```

**Comment by mitchellkrogza** [comment]
@uleodolter just remember the blocker handles requests for anything in your site including a bad bot trying to access robots.txt so just let the blocker block them instead of trying to pass bots to a different robots.txt file, just block them outright on any and everything they access. This still does not however explain why your Android is being blocked. :thinking: 

Which version of the blocker are you using? 2.2 or 2.4 ??

**Comment by uleodolter** [comment]
the problem is when i block `<Location />` at least my mobile device is blocked.  i limited to `<Location /robots.txt>` because blocked false positives is a problem for this site.  sending robots.txt as error document is maybe not the best idea, but its not the reason why 403.

i am running apache-2.4.6 on centos 7

i only added some ip ranges to custom.d/whitelist-ips.conf (but not 127.0.0.1).  access from one of these ip ranges always works, regardless of user-agent.

**Comment by mitchellkrogza** [comment]
Difficult to diagnose this because I cannot replicate it. 

- What is the web site built with, CMS etc?

- What false positives are you experiencing on the site that you cannot use the `<Location />` block as the blocker is designed to use?

**Comment by uleodolter** [comment]
i try to drill down the configuration on second host and keep you update. 
apache is configured as reverse proxy (ProxyPass) for a custom python application.

**Comment by uleodolter** [comment]
i was able to reproduce the issue on Fedora Core 28, httpd-2.4.34 with out-of-the-box configuration.  

then i downloaded and extracted https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/releases/download/V3.2019.01.1042/Apache_2.4.tar.gz in /etc/httpd and added conf.d/bad-bot.conf:

```
<Location "/">
        # AND-combine with preceding configuration sections  
        AuthMerging And
        # include black list
        Include custom.d/globalblacklist.conf
</Location>

```

I can access the site only when using one of the "good_bot".  But wenn accessing using firefox or `curl -A Mozilla http://leodolter.localhost/ i get 403.

```
$ curl -A Mozilla http://leodolter.localhost/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.<br />
</p>
</body></html>
```

```
$ curl -A googlebot http://leodolter.localhost/
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>leodolter.obvsg.at</title>
<body>
  <h1>Hello World!</h1>
</body>
</html>
```

**Comment by uleodolter** [comment]
i think the logic for apache 2.4 is broken, see the attached authz_core:debug messages

[authz_core_debug.log](https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/files/2856040/authz_core_debug.log)

the first RequireAll is denied because because of `Require ip ...` at end of `custom.d/blacklist-ips.conf`,  the second RequiryAny is denied because my ip 192.168.3.58 is not whitelisted and my agent Mozilla is not whitelisted.   

there seems to be big a logic problem.

**Comment by uleodolter** [comment]
@mitchellkrogza i would suggest to add another test to .dev-tools/run-curl-tests-2.4.sh using `-A Mozilla` having allowed as expected result.  i my understanding the debug log explains the issue, but maybe i overlooked something.

**Comment by mitchellkrogza** [comment]
@uleodolter new test for `Mozilla` added, waiting on Travis-CI results

**Comment by mitchellkrogza** [comment]
Ok @uleodolter we have a definite bug here with `Mozilla` and tracing this down is proving tricky. The additional curl test does indeed fail detecting `Mozilla` - https://travis-ci.org/mitchellkrogza/apache-ultimate-bad-bot-blocker/jobs/493226643#L7190-L7192

Going to add same test to 2.2 version to see if this is version independent or not.

**Comment by mitchellkrogza** [comment]
Ok it's 2.4 Specific - test passes on 2.2 and fails on 2.4 :thinking: 

For now until this can be resolved please use the 2.2 version using the module access_compat which allows it to run on Apache 2.4 ....  Apache 2.4 unfortunately is really becoming a troublesome child.

**Comment by mitchellkrogza** [comment]
@davcpas1234 any ideas on this one? I'm thinking it has something to do with the regex format which 2.4 does not like :thinking:

**Comment by davcpas1234** [comment]
@mitchellkrogza I'll take a look and report back, seems probable but will investigate.

**Comment by uleodolter** [comment]
Did you look at the debug log and my comments ?   I think the first `RequireAll` can never be granted because at the end of `custom.d/blacklist-ips.conf` the are multiple `Require ip ...`.  There can be exactly on of them or none of them true, but never ALL  of them.  Therefore the `RequireAll` makes no sense at all.

```
<RequireAny>
    <RequireAll>
        Require all granted
        Require not ...
        Include custom.d/blacklist-ips.conf
   </RequireAll>
```

```
$ tail -n10 blacklist-ips.conf
Require ip 4.17.135.32/27
Require ip 38.0.0.0/8
Require ip 63.144.0.0/13
Require ip 65.112.0.0/12
Require ip 65.192.0.0/11
Require ip 65.213.208.128/27
Require ip 65.222.176.96/27
Require ip 65.222.185.72/29
Require ip 206.2.138.0/23
Require ip 208.71.164.0/22
```

**Comment by mitchellkrogza** [comment]
@uleodolter thanks I missed that debug log, have removed the `require all granted` and running a test to see what happens.

**Comment by mitchellkrogza** [comment]
@uleodolter please test latest release, still have not isolated the Mozilla bug but test the removal of `require all granted`

**Comment by mitchellkrogza** [comment]
@uleodolter this suggestion of removing require all granted introduced breaking changes for users. We have numerous people using 2.4 without issues. It's best you check for permissions you have granted elsewhere that are breaking the current logic.

**Comment by uleodolter** [comment]
@mitchellkrogza my suggestions was not to remove `Require all granted`, that is clearly i bad idea.
 
My suggestion was to remove last 10 lines of blacklist-ips.conf which start by `Require ip` or replace them by `Require not ip ...` if they are really bad ips.   otherwise the overall logic inside RequireAll makes no sense.  I tried both options and then all tests from run-curl-tests-2.4.sh show PASSED.

**Comment by mitchellkrogza** [comment]
:see_no_evil: can't believe I've never spotted that stupid logic

**Comment by uleodolter** [comment]
even for apache 2.2 the `Allow from ...` at the end of blacklist-ips.conf are somewhat confusing, i think it makes no difference when they are removed, or commented and changed to `Deny from ...`,  because of the general `Allow from all` at the begin.  for apache 2.2 additional allow from don't hurt.

**Comment by mitchellkrogza** [comment]
Thank you @uleodolter I cannot believe how I messed up all the logic with that include, it has been addresses and tested and future builds will fail if any of the tests fail now. 

@davcpas1234 please take note of this, **ALL USERS need to update their blacklist-ips.conf** include file both Apache 2.4 and 2.2 as I also discovered a stupid mistake in the Apache 2.2 version this morning.

**Comment by mitchellkrogza** [comment]
@uleodolter I did make corrections in the 2.2 version of blacklist-ips.conf yesterday please confirm. I stupidly also had "require" statements in the 2.2 version
