### ISSUE TITLE
Can't reload fail2ban

### ISSUE THREAD

**Issue by Solidjeuh** [mitchellkrogza/apache-ultimate-bad-bot-blocker#114]
Hello,

I uploaded the fail2ban files, and added the code in "jail.local"
But when I reload fail2ban I get this error:

[root@vps1704859 ~]# fail2ban-client reload
ERROR  Failed during configuration: Bad value substitution:
        section: [apacherepeatoffender]
        option : logpath
        key    : apache_access_log
        rawval :

**Comment by mitchellkrogza** [comment]
Have you specified how your jail.conf or jail.local accesses your log files?? Look at the section of your jail.local 
```
[INCLUDES]

before = paths-debian.conf
```

It might be set to paths-debian.conf or paths-common.conf .... depending which one has been specified, go and inspect that file to see where the paths are pointing to

**Comment by Solidjeuh** [comment]
Hmz I have:

**Jail.conf**
`# Fail2Ban jail base specification file
#
# HOW TO ACTIVATE JAILS:
#
# YOU SHOULD NOT MODIFY THIS FILE.
#
# It will probably be overwitten or improved in a distribution update.
#
# Provide customizations in a jail.local file or a jail.d/customisation.local.
# For example to change the default bantime for all jails and to enable the
# ssh-iptables jail the following (uncommented) would appear in the .local file.
# See man 5 jail.conf for details.
#
# [DEFAULT]
# bantime = 3600
#
# [ssh-iptables]
# enabled = true



# Comments: use '#' for comment lines and ';' (following a space) for inline comments

# The DEFAULT allows a global definition of the options. They can be overridden
# in each jail afterwards.

[DEFAULT]

# "ignoreip" can be an IP address, a CIDR mask or a DNS host. Fail2ban will not
# ban a host which matches an address in this list. Several addresses can be
# defined using space separator.
ignoreip = 127.0.0.1/8

# "bantime" is the number of seconds that a host is banned.
bantime  = 600

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime  = 600

# "maxretry" is the number of failures before a host get banned.
maxretry = 3

# "backend" specifies the backend used to get files modification.
# Available options are "pyinotify", "gamin", "polling" and "auto".
# This option can be overridden in each jail as well.
#
# pyinotify: requires pyinotify (a file alteration monitor) to be installed.
#              If pyinotify is not installed, Fail2ban will use auto.
# gamin:     requires Gamin (a file alteration monitor) to be installed.
#              If Gamin is not installed, Fail2ban will use auto.
# polling:   uses a polling algorithm which does not require external libraries.
# auto:      will try to use the following backends, in order:
#              pyinotify, gamin, polling.
backend = auto

# "usedns" specifies if jails should trust hostnames in logs,
#   warn when DNS lookups are performed, or ignore all hostnames in logs
#
# yes:   if a hostname is encountered, a DNS lookup will be performed.
# warn:  if a hostname is encountered, a DNS lookup will be performed,
#        but it will be logged as a warning.
# no:    if a hostname is encountered, will not be used for banning,
#        but it will be logged as info.
usedns = no


# This jail corresponds to the standard configuration in Fail2ban.
# The mail-whois action send a notification e-mail with a whois request
# in the body.

[ssh]

enabled  = false
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
logpath  = /var/log/secure
maxretry = 5


# Jail for more extended banning of persistent abusers
# !!! WARNING !!!
#   Make sure that your loglevel specified in fail2ban.conf/.local
#   is not at DEBUG level -- which might then cause fail2ban to fall into
#   an infinite loop constantly feeding itself with non-informative lines
[recidive]

enabled  = false
filter   = recidive
logpath  = /var/log/fail2ban.log
action   = iptables-allports[name=recidive]
bantime  = 604800  ; 1 week
findtime = 86400   ; 1 day
maxretry = 5


`

**jail.local**

[DEFAULT]
ignoreip = 127.0.0.1/8 62.141.44.187 2001:4ba0:cafe:c26::1
maxretry = 2
destemail = Demarieandy@outlook.com
findtime = 60
bantime = 3600

[plesk-apache]
enabled = true

[plesk-apache-badbot]
enabled = true

[plesk-dovecot]
enabled = true

[plesk-horde]
enabled = true

[plesk-panel]
enabled = true

[plesk-postfix]
enabled = true

[plesk-proftpd]
enabled = true

[plesk-roundcube]
enabled = true

[plesk-wordpress]
enabled = true

[recidive]
enabled = true

[ssh]
enabled = true

[plesk-modsecurity]
enabled = true

**Comment by mitchellkrogza** [comment]
Add the INCLUDES section I posted earlier at the top of jail.local

**Comment by Solidjeuh** [comment]
Ok, I added that.
So is it OK now? I see:

[root@vps1704859 ~]# touch /etc/fail2ban/apache.repeatoffender
[root@vps1704859 ~]# chmod +x /etc/fail2ban/apache.repeatoffender
[root@vps1704859 ~]# fail2ban-client reload
WARNING 'action' not defined in 'apacherepeatoffender'. Using default one: ''
WARNING No actions were defined for apacherepeatoffender

**Comment by mitchellkrogza** [comment]
Never used this on Plesk so can't offer much help but clearly their error does not like the INCLUDES section being added. The paths are therefore specified elsewhere in Plesk

**Comment by Solidjeuh** [comment]
I think this needs an update, the instructions are for an older fail2ban. This is what I have

Fail2Ban v0.9.6
System: Linux 3.10.0-042stab138.1 • Forum versie: 3.2.7
Web Server: Apache
PHP: 7.2.19
Database server: MySQL(i) 5.5.60-MariaDB
System: Redhat

**Comment by mitchellkrogza** [comment]
Hi @Solidjeuh it's been tested on `Fail2Ban 0.9.6` and I am still using it right now on `Fail2Ban v0.10.2` without any modifications

**Comment by Solidjeuh** [comment]
Well, it's not working

When I add this to the bottom of "/ets/fail2ban/jail.conf" I cannot restart fail2ban.
When I remove the code, I can restart fail2ban.

[apacherepeatoffender]
enabled = true
logpath = %(apache_access_log)s
filter = apacherepeatoffender
banaction = apacherepeatoffender
bantime  = 86400   ; 1 day
findtime = 604800   ; 1 week
maxretry = 20

I uploaded those 2 files, created and cmodded : apache.repeatoffender

**Comment by mitchellkrogza** [comment]
@Solidjeuh please can you run these in this order to see where it is failing.

`sudo service fail2ban stop`
`sudo fail2ban-client -vvv -x stop`
`sudo fail2ban-client -vvv -x start`

This will show you at what point it is failing. Once you have that error message you can post it here. 

Then to restart Fail2ban again

`sudo service fail2ban restart`

**Comment by Solidjeuh** [comment]
[root@vps1704859 ~]# sudo touch /etc/fail2ban/apache.repeatoffender
[root@vps1704859 ~]# chmod +x /etc/fail2ban/apache.repeatoffender
[root@vps1704859 ~]# sudo systemctl restart fail2ban
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.


[root@vps1704859 ~]# sudo service fail2ban stop
Redirecting to /bin/systemctl stop fail2ban.service
[root@vps1704859 ~]# sudo fail2ban-client -vvv -x stop
INFO   Loading configs for fail2ban under /etc/fail2ban
DEBUG  Reading configs for fail2ban under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
Level 7     Reading file: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
Level 7     Shared file: /etc/fail2ban/fail2ban.conf
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
ERROR  Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?



[root@vps1704859 ~]# sudo fail2ban-client -vvv -x start
INFO   Loading configs for fail2ban under /etc/fail2ban
DEBUG  Reading configs for fail2ban under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
Level 7     Reading file: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
Level 7     Shared file: /etc/fail2ban/fail2ban.conf
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
INFO   Loading configs for jail under /etc/fail2ban
DEBUG  Reading configs for jail under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/jail.conf, /etc/fail2ban/jail.d/plesk.conf, /etc/fail2ban/jail.local
INFO     Loading files: ['/etc/fail2ban/jail.conf']
Level 7     Reading file: /etc/fail2ban/jail.conf
INFO     Loading files: ['/etc/fail2ban/jail.d/plesk.conf']
Level 7     Reading file: /etc/fail2ban/jail.d/plesk.conf
INFO     Loading files: ['/etc/fail2ban/jail.local']
Level 7     Reading file: /etc/fail2ban/jail.local
INFO     Loading files: ['/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.d/plesk.conf', '/etc/fail2ban/jail.local']
Level 7     Shared file: /etc/fail2ban/jail.conf
Level 7     Shared file: /etc/fail2ban/jail.d/plesk.conf
Level 7     Shared file: /etc/fail2ban/jail.local
INFO   Loading configs for filter.d/sshd under /etc/fail2ban
DEBUG  Reading configs for filter.d/sshd under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/sshd.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/sshd.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/sshd.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/common.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/common.local']
Level 7     Reading file: /etc/fail2ban/filter.d/common.local
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/sshd.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/common.conf
Level 7     Shared file: /etc/fail2ban/filter.d/sshd.conf
Level 7 Non essential option 'logencoding' not defined in 'ssh'.
Level 7 Non essential option 'failregex' not defined in 'ssh'.
Level 7 Non essential option 'ignoreregex' not defined in 'ssh'.
Level 7 Non essential option 'ignorecommand' not defined in 'ssh'.
INFO   Loading configs for action.d/iptables under /etc/fail2ban
DEBUG  Reading configs for action.d/iptables under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/action.d/iptables.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables.conf']
Level 7     Reading file: /etc/fail2ban/action.d/iptables.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.conf']
Level 7     Reading file: /etc/fail2ban/action.d/iptables-common.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-blocktype.local']
Level 7     Reading file: /etc/fail2ban/action.d/iptables-blocktype.local
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.local']
Level 7     Reading file: /etc/fail2ban/action.d/iptables-common.local
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.conf', '/etc/fail2ban/action.d/iptables.conf']
Level 7     Shared file: /etc/fail2ban/action.d/iptables-common.conf
Level 7     Shared file: /etc/fail2ban/action.d/iptables.conf
INFO   Loading configs for filter.d/recidive under /etc/fail2ban
DEBUG  Reading configs for filter.d/recidive under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/recidive.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/recidive.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/recidive.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/recidive.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/common.conf
Level 7     Shared file: /etc/fail2ban/filter.d/recidive.conf
Level 7 Non essential option 'logencoding' not defined in 'recidive'.
Level 7 Non essential option 'failregex' not defined in 'recidive'.
Level 7 Non essential option 'ignoreregex' not defined in 'recidive'.
Level 7 Non essential option 'ignorecommand' not defined in 'recidive'.
INFO   Loading configs for action.d/iptables-allports under /etc/fail2ban
DEBUG  Reading configs for action.d/iptables-allports under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/action.d/iptables-allports.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-allports.conf']
Level 7     Reading file: /etc/fail2ban/action.d/iptables-allports.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.conf', '/etc/fail2ban/action.d/iptables-allports.conf']
Level 7     Shared file: /etc/fail2ban/action.d/iptables-common.conf
Level 7     Shared file: /etc/fail2ban/action.d/iptables-allports.conf
INFO   Loading configs for filter.d/proftpd under /etc/fail2ban
DEBUG  Reading configs for filter.d/proftpd under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/proftpd.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/proftpd.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/proftpd.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/proftpd.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/common.conf
Level 7     Shared file: /etc/fail2ban/filter.d/proftpd.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-proftpd'.
Level 7 Non essential option 'failregex' not defined in 'plesk-proftpd'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-proftpd'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-proftpd'.
INFO   Loading configs for action.d/iptables-multiport under /etc/fail2ban
DEBUG  Reading configs for action.d/iptables-multiport under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/action.d/iptables-multiport.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-multiport.conf']
Level 7     Reading file: /etc/fail2ban/action.d/iptables-multiport.conf
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.conf', '/etc/fail2ban/action.d/iptables-multiport.conf']
Level 7     Shared file: /etc/fail2ban/action.d/iptables-common.conf
Level 7     Shared file: /etc/fail2ban/action.d/iptables-multiport.conf
INFO   Loading configs for filter.d/postfix-sasl under /etc/fail2ban
DEBUG  Reading configs for filter.d/postfix-sasl under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/postfix-sasl.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/postfix-sasl.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/postfix-sasl.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/postfix-sasl.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/common.conf
Level 7     Shared file: /etc/fail2ban/filter.d/postfix-sasl.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-postfix'.
Level 7 Non essential option 'failregex' not defined in 'plesk-postfix'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-postfix'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-postfix'.
INFO   Loading configs for filter.d/plesk-dovecot under /etc/fail2ban
DEBUG  Reading configs for filter.d/plesk-dovecot under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/plesk-dovecot.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-dovecot.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/plesk-dovecot.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/plesk-dovecot.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/common.conf
Level 7     Shared file: /etc/fail2ban/filter.d/plesk-dovecot.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-dovecot'.
Level 7 Non essential option 'failregex' not defined in 'plesk-dovecot'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-dovecot'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-dovecot'.
INFO   Loading configs for filter.d/plesk-horde under /etc/fail2ban
DEBUG  Reading configs for filter.d/plesk-horde under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/plesk-horde.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-horde.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/plesk-horde.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-horde.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/plesk-horde.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-horde'.
Level 7 Non essential option 'failregex' not defined in 'plesk-horde'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-horde'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-horde'.
INFO   Loading configs for filter.d/plesk-roundcube under /etc/fail2ban
DEBUG  Reading configs for filter.d/plesk-roundcube under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/plesk-roundcube.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-roundcube.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/plesk-roundcube.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-roundcube.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/plesk-roundcube.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-roundcube'.
Level 7 Non essential option 'failregex' not defined in 'plesk-roundcube'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-roundcube'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-roundcube'.
INFO   Loading configs for filter.d/apache-auth under /etc/fail2ban
DEBUG  Reading configs for filter.d/apache-auth under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/apache-auth.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apache-auth.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/apache-auth.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apache-common.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/apache-common.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apache-common.local']
Level 7     Reading file: /etc/fail2ban/filter.d/apache-common.local
INFO     Loading files: ['/etc/fail2ban/filter.d/apache-common.conf', '/etc/fail2ban/filter.d/apache-auth.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/apache-common.conf
Level 7     Shared file: /etc/fail2ban/filter.d/apache-auth.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-apache'.
Level 7 Non essential option 'failregex' not defined in 'plesk-apache'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-apache'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-apache'.
INFO   Loading configs for filter.d/apache-badbots under /etc/fail2ban
DEBUG  Reading configs for filter.d/apache-badbots under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/apache-badbots.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apache-badbots.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/apache-badbots.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apache-badbots.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/apache-badbots.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-apache-badbot'.
Level 7 Non essential option 'failregex' not defined in 'plesk-apache-badbot'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-apache-badbot'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-apache-badbot'.
INFO   Loading configs for filter.d/plesk-panel under /etc/fail2ban
DEBUG  Reading configs for filter.d/plesk-panel under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/plesk-panel.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-panel.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/plesk-panel.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-panel.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/plesk-panel.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-panel'.
Level 7 Non essential option 'failregex' not defined in 'plesk-panel'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-panel'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-panel'.
INFO   Loading configs for filter.d/plesk-modsecurity under /etc/fail2ban
DEBUG  Reading configs for filter.d/plesk-modsecurity under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/plesk-modsecurity.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-modsecurity.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/plesk-modsecurity.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-modsecurity.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/plesk-modsecurity.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-modsecurity'.
Level 7 Non essential option 'failregex' not defined in 'plesk-modsecurity'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-modsecurity'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-modsecurity'.
INFO   Loading configs for filter.d/plesk-wordpress under /etc/fail2ban
DEBUG  Reading configs for filter.d/plesk-wordpress under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/plesk-wordpress.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-wordpress.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/plesk-wordpress.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/plesk-wordpress.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/plesk-wordpress.conf
Level 7 Non essential option 'logencoding' not defined in 'plesk-wordpress'.
Level 7 Non essential option 'failregex' not defined in 'plesk-wordpress'.
Level 7 Non essential option 'ignoreregex' not defined in 'plesk-wordpress'.
Level 7 Non essential option 'ignorecommand' not defined in 'plesk-wordpress'.
WARNING 'filter' not defined in 'sshd'. Using default one: ''
WARNING No filter set for jail sshd
Level 7 Non essential option 'logpath' not defined in 'sshd'.
Level 7 Non essential option 'logencoding' not defined in 'sshd'.
Level 7 Non essential option 'failregex' not defined in 'sshd'.
Level 7 Non essential option 'ignoreregex' not defined in 'sshd'.
Level 7 Non essential option 'ignorecommand' not defined in 'sshd'.
WARNING 'filter' not defined in 'sshd'. Using default one: ''
WARNING 'action' not defined in 'sshd'. Using default one: ''
WARNING No actions were defined for sshd
WARNING 'filter' not defined in 'nginx-http-auth'. Using default one: ''
WARNING No filter set for jail nginx-http-auth
Level 7 Non essential option 'logpath' not defined in 'nginx-http-auth'.
Level 7 Non essential option 'logencoding' not defined in 'nginx-http-auth'.
Level 7 Non essential option 'failregex' not defined in 'nginx-http-auth'.
Level 7 Non essential option 'ignoreregex' not defined in 'nginx-http-auth'.
Level 7 Non essential option 'ignorecommand' not defined in 'nginx-http-auth'.
WARNING 'filter' not defined in 'nginx-http-auth'. Using default one: ''
WARNING 'action' not defined in 'nginx-http-auth'. Using default one: ''
WARNING No actions were defined for nginx-http-auth
INFO   Loading configs for filter.d/apacherepeatoffender under /etc/fail2ban
DEBUG  Reading configs for filter.d/apacherepeatoffender under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/apacherepeatoffender.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apacherepeatoffender.conf']
Level 7     Reading file: /etc/fail2ban/filter.d/apacherepeatoffender.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/apacherepeatoffender.conf']
Level 7     Shared file: /etc/fail2ban/filter.d/apacherepeatoffender.conf
ERROR  Failed during configuration: Bad value substitution:
        section: [apacherepeatoffender]
        option : logpath
        key    : apache_access_log
        rawval :

**Comment by mitchellkrogza** [comment]
Very easy to fix, you've not defined apache_access_logs by means of the required includes

Example:
[INCLUDES]
before = paths-common.conf

Or

[INCLUDES]
before = paths-debian.conf

Alternatively you can hard code the location like this

[apacherepeatoffender]
enabled = true
logpath = /var/log/apache/*.log
filter = apacherepeatoffender
banaction = apacherepeatoffender
bantime = 86400 ; 1 day
findtime = 604800 ; 1 week
maxretry = 20

**Comment by Solidjeuh** [comment]
Yes, that's it. It works with:

[INCLUDES]
before = paths-debian.conf

[apacherepeatoffender]
enabled = true
logpath = %(apache_access_log)s
filter = apacherepeatoffender
banaction = apacherepeatoffender
bantime  = 86400   ; 1 day
findtime = 604800   ; 1 week
maxretry = 20

Thank you for the help and the great addon !! :)

**Comment by mitchellkrogza** [comment]
Great glad it's working I'll update the docs to make note about this for others

**Comment by Solidjeuh** [comment]
Sorry, New error in PLESK Fail2Ban

f2bmng failed: ERROR:__main__:No option 'enabled' in section: 'INCLUDES'.

**Comment by Solidjeuh** [comment]
Okay this is it, all good. :)

[INCLUDES]
before = paths-debian.conf
enabled = true

[apacherepeatoffender]
enabled = true
logpath = %(apache_access_log)s
filter = apacherepeatoffender
banaction = apacherepeatoffender
bantime = 86400 ; 1 day
findtime = 604800 ; 1 week
maxretry = 20

**Comment by mitchellkrogza** [comment]
Great @Solidjeuh 

For future reference the default enabled statement should be false and then you just activate jails individually. By saying enabled = true in the [INCLUDES] section you enable everything.

So your config should be

```
[INCLUDES]
before = paths-debian.conf
enabled = true```

and then

```
[jail1]
enabled = true

[jail2]
enabled = false

[jail3]
enabled = true

etc etc
```

**Comment by Solidjeuh** [comment]
So something like this https://i.imgur.com/zz20XnK.jpg ?

**Comment by mitchellkrogza** [comment]
Not so sure with Plesk how they have configured things. As I always say, just test, otherwise leave the default as "enabled = true"

**Comment by Solidjeuh** [comment]
I looked at the Fail2Ban logs, and I think everything is good there. IP's are still getting banned correctly. I see no problems so far. Thank you for all the help :)

```
2019-06-19 15:20:11,171 fail2ban.actions        [24505]: NOTICE  [ssh] Ban 93.55.209.46
2019-06-19 15:20:11,174 fail2ban.filter         [24505]: WARNING Unable to find a corresponding IP address for 2001:4ba0:cafe:c26::1: [Errno -9] Address family for hostname not supported
2019-06-19 15:20:11,174 fail2ban.filter         [24505]: INFO    [recidive] Found 93.55.209.46
2019-06-19 15:20:13,665 fail2ban.filter         [24505]: WARNING Unable to find a corresponding IP address for 2001:4ba0:cafe:c26::1: [Errno -9] Address family for hostname not supported
2019-06-19 15:20:13,666 fail2ban.filter         [24505]: INFO    [ssh] Found 142.93.149.119
2019-06-19 15:20:13,676 fail2ban.filter         [24505]: WARNING Unable to find a corresponding IP address for 2001:4ba0:cafe:c26::1: [Errno -9] Address family for hostname not supported
2019-06-19 15:20:13,676 fail2ban.filter         [24505]: INFO    [ssh] Found 142.93.149.119
2019-06-19 15:20:15,823 fail2ban.filter         [24505]: WARNING Unable to find a corresponding IP address for 2001:4ba0:cafe:c26::1: [Errno -9] Address family for hostname not supported
2019-06-19 15:20:15,824 fail2ban.filter         [24505]: INFO    [ssh] Found 142.93.149.119
2019-06-19 15:20:16,764 fail2ban.filter         [24505]: WARNING Unable to find a corresponding IP address for 2001:4ba0:cafe:c26::1: [Errno -9] Address family for hostname not supported
2019-06-19 15:20:16,764 fail2ban.filter         [24505]: INFO    [ssh] Found 142.93.149.119
2019-06-19 15:20:16,772 fail2ban.filter         [24505]: WARNING Unable to find a corresponding IP address for 2001:4ba0:cafe:c26::1: [Errno -9] Address family for hostname not supported
2019-06-19 15:20:16,773 fail2ban.filter         [24505]: INFO    [ssh] Found 142.93.149.119
2019-06-19 15:20:17,392 fail2ban.actions        [24505]: NOTICE  [ssh] Ban 142.93.149.119
```

**Comment by mitchellkrogza** [comment]
Excellent enjoy what it will do for you :wink:
