### ISSUE TITLE
 <RequireAll> directive contains only negative authorization directives

### ISSUE THREAD

**Issue by lyquix-owner** [mitchellkrogza/apache-ultimate-bad-bot-blocker#116]
Hi Mitchell: I have severs that automatically download globalblacklist.conf for Apache 2.4, and it seems like the latest version is producing an error that is preventing Apache from starting:

```
AH01624: <RequireAll> directive contains only negative authorization directives
AH00014: Configuration check failed
Action 'configtest' failed.
```

I have not troubleshooted the issue yet, just disabled globalblacklist.conf for now, but I thought you may want to know.

I will add comments here if I find the cause of the issue.

**Comment by lyquix-owner** [comment]
Looks like it caused by this line being commented:

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/de742add64f72b8c04f434ad2b470fde9f24437d#diff-b6cbaafb7681503b7427805d312fb12f

`Require all granted`

**Comment by mitchellkrogza** [comment]
Apologies @lyquix-owner new build in progress reversing earlier change. Sincere apologies.

**Comment by lyquix-owner** [comment]
No worries, thank you for such an amazing repo!
