### ISSUE TITLE
[BUG] CFNetwork has a legit use case

### ISSUE THREAD

**Issue by GieltjE** [mitchellkrogza/apache-ultimate-bad-bot-blocker#120]
**Describe the bug**
Safari uses the following user agent (chaning numbers according to the iOS build) to get bookmark updates "MobileSafari/604.1 CFNetwork/976 Darwin/18.2.0".
The CFNetwork is mentioned in the bad user agent list as "Cfnetwork" (different casing).
This causes legit users to be blocked with a 403/AH01630 message which in turn causes fail2ban to pick them up.

**To Reproduce**
Use an iphone or similar to bookmark a website, once in a while the server will be queried with the aformentioned user agent.

**Expected behavior**
CFNetwork appears to be a legit apple network probably used for many other good things, shouldn't be blocked as far as I can see.

**Server (please complete the following information):**
 - OS: Debian testing
 - Apache Version: 2.4.38
 - Other Environments: n/a

**Comment by mitchellkrogza** [comment]
Thanks for reporting this @GieltjE  fixed in latest commit

**Comment by GieltjE** [comment]
Shouldn't it be removed from the other files to?

**Comment by mitchellkrogza** [comment]
Where else? @GieltjE it's removed from bad-user-agents.list and the new build is currently in progress, when the build completes (approx 8 minutes) all files will be updated.

Used by a number of other legitimate user-agent see : https://developers.whatismybrowser.com/useragents/explore/operating_system_name/darwin/

**Comment by mitchellkrogza** [comment]
@GieltjE build completed > https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/b80ac130bb9a760cf8c3193e8697a8aa6d5a1c15 please update and confirm

**Comment by GieltjE** [comment]
Confirmed, thanks for your quick replies!
