### ISSUE TITLE
diff issue with syntax in latest release

### ISSUE THREAD

**Issue by jswails** [mitchellkrogza/apache-ultimate-bad-bot-blocker#127]
**Describe the bug**
here is the offending area where it fails:

 diff <(wget -q -O - ${BLACKLIST_URL}) ${APACHE_CONF}/globalblacklist.conf;
  DIFF_CHECK=$?
  if [ ${DIFF_CHECK} -eq 0 ] ; then

here is the error I get:

/usr/sbin/update-apacheblocker.sh: 65: /usr/sbin/update-apacheblocker.sh: Syntax error: "(" unexpected

**To Reproduce**
pulled down the latest code from 3 days ago and then today and it still has the same issue.

**Expected behavior**
for it to work :)

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu, Arch, CentOS] Ubuntu 18.04
 - Apache Version [post output of apachectl -V or httpd -v] not an apache issue
 - Other Environments [e.g. Plesk, CPanel - include Version] i dont use any managment software. its all clean.
 - Any applicable error messages.

**Additional information**

here is my version of diff on the server:

 diff -v
diff (GNU diffutils) 3.6
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.

**Comment by mitchellkrogza** [comment]
Any reason for closing? Did you solve this?

**Comment by jswails** [comment]
Its weird. After I opened that issue  it suddenly started working.
Strangest thing. Must have been environmental. Appreciate the follow-up and
your work. Very well done.

**Comment by mitchellkrogza** [comment]
Great glad it's solved and glad the blocker is helping you. Some new enhancements, better regex and better build testing coming soon.

**Comment by Lerrissirrel** [comment]
For anyone who comes along, one possible cause of this is trying to run the script manually with "sh" rather than "bash".   I get that error with sh but not with bash (or just running it directly since it include #!/bin/bash ) on my openSUSE Leap 15.6 system.
