### ISSUE TITLE
[INSTALLATION] How to

### ISSUE THREAD

**Issue by ZerooCool** [mitchellkrogza/apache-ultimate-bad-bot-blocker#128]
Can you explain to me how you did to draw up your BadBot list?

It comes from your logs, or, it is made available from a web service on which I can rely, to regularly update an updated list?

Thanks for this work, maintained, with an impressive list of BadBot.

**Comment by mitchellkrogza** [comment]
It's taken years to build the lists and maintain them, mostly all from daily logs.
