### ISSUE TITLE
[SYNTAXE] line 7286 : – or -

### ISSUE THREAD

**Issue by ZerooCool** [mitchellkrogza/apache-ultimate-bad-bot-blocker#131]
I often had problems copying paste or I found myself with big dashes instead of small dashes. Is it important here? I would rather use the dashes. I do not know about Apache's syntax, which is preferable.
For my part, I used the little dash and it works.

RewriteRule ^(.*)$ – [F,L]

or use

RewriteRule ^(.*)$ - [F,L]

**Comment by mitchellkrogza** [comment]
Don't copy and paste, you seem to do a lot of that. Always grab files from here using curl or wget do not copy and paste
