### ISSUE TITLE
[FALSE POSITIVE] what's up with 'eladkarako' domains

### ISSUE THREAD

**Issue by eladkarako** [mitchellkrogza/apache-ultimate-bad-bot-blocker#135]
on `custom.d/globalblacklist.conf`
I happened to found both of my domains (`eladkarako.com` and `eladkarako.github.io`) on that filter, and I was interested to know where did you come-by this filter, in-case you've copied it from somewhere.

**Comment by mitchellkrogza** [comment]
@eladkarako I will have to check how they entered this list.

**Comment by mitchellkrogza** [comment]
Apologies for only dealing with this now. Removed in latest commit.
