### ISSUE TITLE
[ADD/REMOVE] Missing some UC Berkeley Scanner IPs & Consolidate Cyveillance

### ISSUE THREAD

**Issue by Jas0n99** [mitchellkrogza/apache-ultimate-bad-bot-blocker#136]
You only list 1 IP of the berkeley scanner (169.229.3.91) but there are several more:

**169.229.3.89** - researchscan-gw.eecs.Berkeley.edu
**169.229.3.90** - researchscan0.eecs.berkeley.edu
**169.229.3.91** - researchscan1.eecs.berkeley.edu
**169.229.3.92** - researchscan2.eecs.berkeley.edu
**169.229.3.93** - researchscan3.eecs.berkeley.edu
**169.229.3.94** - researchscan4.eecs.berkeley.edu

Or if you want a single CIDR netblock: **169.229.3.88/29**

Also, the Cyveillance list has some redundant IPs:

65.213.208.128/27
65.222.176.96/27
65.222.185.72/29

Are all technically within the existing **65.192.0.0/11** netblock (65.192.0.0 - 65.223.255.255).

**Comment by mitchellkrogza** [comment]
Thanks @Jas0n99 will update it I think the single CIDR is best
