### ISSUE TITLE
Maxthon browser blocked

### ISSUE THREAD

**Issue by DarkZeroCD** [mitchellkrogza/apache-ultimate-bad-bot-blocker#14]
Hello,
It seems to me that the Maxthon browser is blocked.

**Comment by mitchellkrogza** [comment]
Hmm interesting, do you perhaps have the User-Agent string for that browser so I can check why it is being blocked.

**Comment by mitchellkrogza** [comment]
Found it L359 > BrowserMatchNoCase "Maxthon" bad_bot
Will be removed in today's commit.

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/bfbe1c308fd2a6f0f95a1b674514aec4722a1357
