### ISSUE TITLE
Improve Fail2Ban

### ISSUE THREAD

**Issue by DarkZeroCD** [mitchellkrogza/apache-ultimate-bad-bot-blocker#16]
Hello,
Is it possible to improve Fail2Ban to block recurrence over a longer period of time.
A blocking day is good to block the bots that abuse, but those who scan each of the pages of my site are really annoying.
Because they come back all the time.

Thanks for all the work you do!

**Comment by mitchellkrogza** [comment]
Hi @DarkZeroCD thanks for your support and glad the blocker is helping you. Sure it's easy to change that.

just change bantime and restart fail2ban. 

```
604800  ;1 week
2592000  ;30 days
-1  ;forever
```
You can also change maxretry to a lower value like "10" and block them even quicker.

```
[apacherepeatoffender]
enabled = true
logpath = %(apache_access_log)s
filter = apacherepeatoffender
banaction = apacherepeatoffender
bantime  = 604800   ; 1 week
findtime = 604800   ; 1 week
maxretry = 20
```
