### ISSUE TITLE
[INSTALLATION] (Updates issue)

### ISSUE THREAD

**Issue by lunaraurora** [mitchellkrogza/apache-ultimate-bad-bot-blocker#160]
Hello i have installed (and it works) apache ultimate bbb 2.4+ on a centos 7, but i'm not sure why i always receive the .log setted via cron (/usr/sbin/update-apacheblocker.sh) with multiple entries saying 'Bad bot globalblacklist is already up to date' (from a month or so).
It seems i no longer receive updates, i had to set anonymousfox.com manually inside the bad-referrer-words.conf list, but when i update with update-apacheblocker.sh (is executable) also says 'Bad bot globalblacklist is already up to date'. The only way to get a response with successful updates is to insert them directly inside the file globalblacklist.conf and then run the update, in this way the update works, but they are subsequently removed from the list ..i'm not sure about what is wrong in my config, any help is apprecciated

Thanks

**Comment by mitchellkrogza** [comment]
Hi @lunaraurora there has not been any updates since July when Travis-CI became such a massive problem and stopped working. I just haven't time to migrate the build script to Github Actions yet but there has not been many new additions at all so the lists as are are still GOOD

**Comment by lunaraurora** [comment]
@mitchellkrogza this makes sense, I hope you don't leave this project which is a great asset for all of us, thanks for your work!

**Comment by mitchellkrogza** [comment]
> @mitchellkrogza this makes sense, I hope you don't leave this project which is a great asset for all of us, thanks for your work!

I'll get the builds back online soon, I manually added a new version for Litespeed users today.
