### ISSUE TITLE
CentOS 6.8 and Plesk 12.5

### ISSUE THREAD

**Issue by stevetoza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#17]
Hello, 

I have a new challenge for you :) Im trying to get this working with Plesk version 12.5. Put I dont seem to be getting much success when curling the blocked user agents against domains we have setup still getting the 200 status code. I have included the .conf file in /etc/httpd/conf/httpd.conf.

I have had to place the files in a custom location (/etc/httpd/custom.d) as Plesk auto includes the conf.d by default and was including them twice.  

When you get chance could you have a look. 

Thanks

**Comment by mitchellkrogza** [comment]
Never worked with Plesk, I need to see your complete httpd.conf file. You can for privacy sake just email it to me on mitchellkrog@gmail.com

**Comment by mitchellkrogza** [comment]
Did you note the changes made to the CentOS 6 config in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/78a8c521cc184786d3a391e75437fda47acc63fc

**Comment by stevetoza** [comment]
Will email over my httpd.conf shortly. Implemented the changes to a different folder /etc/httpd/custom.d for the global files.

**Comment by mitchellkrogza** [comment]
Cool, I'll have a look when I get it.

**Comment by stevetoza** [comment]
Email sent might have ended up in your spam folder :)

**Comment by mitchellkrogza** [comment]
I will have to try find some time to play with Plesk in a VM. Seems it really does not play nicely with Apache.

**Comment by mitchellkrogza** [comment]
@stevetoza have you ever had any success with this?

**Comment by stevetoza** [comment]
@mitchellkrogza nope didnt get very far at all 👎

**Comment by mitchellkrogza** [comment]
Hi @stevetoza will see if I can find some time to still look into this, been a mad couple of months since you asked about this and I was very ill for about 2 months. I have CentOS in a VM just need to get Plesk and have a look through it's config's. Will let you know.

**Comment by mitchellkrogza** [comment]
@stevetoza remind me please which edition of Plesk you are using? Web Host / Web Pro / Web Admin ???

**Comment by stevetoza** [comment]
@mitchellkrogza No worries, I hope you're feeling better now and back to normal. Using Plesk 17.5.3 web host edition.

**Comment by mitchellkrogza** [comment]
@stevetoza got a new trial and thankfully they have a complete ISO including Plesk + Cent so busy building a VM now with it. 
![screen shot 2017-10-25 at 12 26 19 pm](https://user-images.githubusercontent.com/9961541/31994120-dcf1c51c-b97f-11e7-8e7c-8f5b6d797a13.png)

**Comment by stevetoza** [comment]
@mitchellkrogza Thats nice an easy, saying that the install is pretty quick for plesk these days.

**Comment by mitchellkrogza** [comment]
@stevetoza finally after a few attempts, got it all installed including plesk and a lightweight desktop gui. Tomorrow can take a look into Plesk. 👍 

![screen shot 2017-10-25 at 5 51 26 pm](https://user-images.githubusercontent.com/9961541/32008759-55559a1a-b9ad-11e7-94e9-0aa7d746ffc4.png)

**Comment by mitchellkrogza** [comment]
@stevetoza still busy finding my around Plesk but getting there. 

Please tell me something is your Plesk running both Nginx and Apache as per my installation from their ISO ?? 

What I have after installing using their ISO image is the following

![screen shot 2017-10-26 at 4 24 10 pm](https://user-images.githubusercontent.com/9961541/32058402-32eceab0-ba6a-11e7-8874-4844337ecd96.png)


which has Nginx in front doing reverse proxying to the web site which is actually running on Apache in the background on port :7081. 

Can you confirm you have this same configuration on your Plesk install?

Additionally are you looking to be able to add the blocker per individual vhost or global to all vhosts?

**Comment by stevetoza** [comment]
@mitchellkrogza Hello, no worries Plesk is a little different!, Im using plesk with just apache, nginx is not running at all.

Im running CentOS 6.9 and 7.4 on different servers. 

Looking to add the blocker globally to all vhosts.

**Comment by mitchellkrogza** [comment]
Hmmm, not sure how to tell Plesk to just use Apache as the web server and not Nginx.

**Comment by stevetoza** [comment]
If you run the plesk installer from ssh, you can uninstall / remove it that way

**Comment by mitchellkrogza** [comment]
OK I figured that part out, simply navigate to Tools & Settings > Service Management and Stop "Nginx Reverse Proxy" and Apache immediately takes over serving all vhosts. So that was easy enough, now to figure out to add the blocker globally for all Apache sites. I'll find the right way eventually.

**Comment by mitchellkrogza** [comment]
@stevetoza from what I can gather so far it involves creating a custom version of domainVirtualHost.php ...... I'm getting there, their docs are a bit of a mess to be dead honest and as vague as Apache docs themselves :)

**Comment by mitchellkrogza** [comment]
@stevetoza I got it sorted 👍 will post a guide shortly.

**Comment by mitchellkrogza** [comment]
@stevetoza please see > https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/PLESK-ONYX-APACHE-CONFIGURATION.md

A new guide will follow shortly for those wanting to use the blocker on Plesk with Nginx doing reverse proxying to Apache. 

This guide is for Plesk Onyx systems where **Nginx Reverse Proxy** has been **disabled** and only Apache is the main web server.

**Comment by stevetoza** [comment]
@mitchellkrogza Thats awesome, I wil give it a whirl shortly 👍

**Comment by mitchellkrogza** [comment]
@stevetoza great let me know how it goes. I will have a second guide soon for those using the Nginx Reverse Proxy System. Need to get the wiki for this repo up and running as all of these guides, FAQ's etc should be in a nicely laid out wiki.
