### ISSUE TITLE
.htaccess version fatal error?

### ISSUE THREAD

**Issue by Jonras78** [mitchellkrogza/apache-ultimate-bad-bot-blocker#183]
![htaccess](https://user-images.githubusercontent.com/45826954/177753810-48dfb4bf-9772-4d00-9654-144b3c1212b2.jpg)

**Comment by mitchellkrogza** [comment]
That is a setenvif version this version is a normal .htaccess
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_htaccess_versions/htaccess-mod_rewrite.txt
