### ISSUE TITLE
Is auto updating secure?

### ISSUE THREAD

**Issue by Grid405** [mitchellkrogza/apache-ultimate-bad-bot-blocker#186]
I have a question regarding the auto updater bash script, if the repository ever gets compromised and my server automatically pulls a malicious globalblacklist.conf, could that override my server configuration and bypass any security settings like basic auth rules ?

**Comment by mitchellkrogza** [comment]
Nobody can commit here except me. Thousands using this and the Nginx blocker and auto updating daily.
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker
