### ISSUE TITLE
Possible bad bots and IP's

### ISSUE THREAD

**Issue by srmobile** [mitchellkrogza/apache-ultimate-bad-bot-blocker#19]
Here is some possible contributions to include in your module.

The following is a valid website but I never signed up for this service so I suspect it’s a way to look for vulnerabilities:
 
107.22.157.194 - - [11/Apr/2017:12:19:35 -0400] "HEAD / HTTP/1.1" 302 - "-" "Mozilla/5.0 (compatible; phpservermon/3.2.0; +http://www.phpservermonitor.org)"
107.22.157.194 - - [11/Apr/2017:12:19:35 -0400] "HEAD /eng/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (compatible; phpservermon/3.2.0; +http://www.phpservermonitor.org)"
 
 
And a bot looking for word press login:
 
151.62.127.36 - - [09/Apr/2017:03:18:17 -0400] "GET /wp-login.php HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"
151.62.127.36 - - [09/Apr/2017:03:18:18 -0400] "GET /eng/wp-login.php HTTP/1.1" 404 151061 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"

**Comment by mitchellkrogza** [comment]
Wait for next update with custom includes then you can block
phpservermonitor.org
and
151.62.127.36

using the new include files system for custom blocking of your own. Hoped to have that update out this week but have a lot of family drama going on with my Dad dying of cancer so been very tied up with all sorts of medical affairs and personal affairs. 

Being Easter weekend I won't do any major updates as people are away so I will leave this big updates until tuesday or wednesday as it can break people's existing installations especially those using the autoupdate.sh script which will fail when it reloads apache and finds missing and required included files.

Stand by for this update !!!

**Comment by mitchellkrogza** [comment]
@srmobile New Custom Include Files Introduced today in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/releases/tag/2017-04-19.Build-173 PLEASE READ UPDATED INSTRUCTIONS !!!!
