### ISSUE TITLE
[REMOVE] thepokertimer.com

### ISSUE THREAD

**Issue by karolk** [mitchellkrogza/apache-ultimate-bad-bot-blocker#190]
**Is this an Addition / Removal Request?**

Yes

**Please List the User-Agent string or Referrer to be added/removed**

`thepokertimer.com`

**Please explain why it should be added/removed**

It has never engaged in spamming/scraping or any similar behaviour. If there was traffic coming out under this domain it might have been related to shared VPS we were on. 

**Any other important information to consider**

We often get misclassified as a gambling website, which we are not. We supply poker tournament software.

**Comment by mitchellkrogza** [comment]
Removed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/64d9faa1e073ec66dbf2bf4c59534c2977e2a360
