### ISSUE TITLE
Remove oBot - belongs to Uptime Robot

### ISSUE THREAD

**Issue by solaceten** [mitchellkrogza/apache-ultimate-bad-bot-blocker#198]
Hello

Thanks for your superb work.  Ran into some bother with the latest user agent list...

**Removal Request**

https://uptimerobot.com/help/locations/

[Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)](https://explore.whatismybrowser.com/useragents/parse/624921727-uptime-robot)

Appears to be getting caught under oBot.  As soon as I added it, my sites all registered as down, then I commented oBot and they all came back up again!

**Comment by idflorin** [comment]
I've just tested for oBot. Seems like you are right.

> Hello
> 
> Thanks for your superb work. Ran into some bother with the latest user agent list...
> 
> **Removal Request**
> 
> https://uptimerobot.com/help/locations/
> 
> [Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)](https://explore.whatismybrowser.com/useragents/parse/624921727-uptime-robot)
> 
> Appears to be getting caught under oBot. As soon as I added it, my sites all registered as down, then I commented oBot and they all came back up again!

**Comment by mitchellkrogza** [comment]
Hi @solaceten and @idflorin it seems word boundaries are probably causing this.

```
Atomseobot
Discobot
Foobot
````

and a few others, I will test with obot in the whitelist.

**Comment by mitchellkrogza** [comment]
Passed my tests as a good bot
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/actions/runs/8450495137/job/23146774854

**Comment by mitchellkrogza** [comment]
Extra test added and it passes.
Pull the latest globalblacklist.conf

Fixed in
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/9c93e843f27a522a482fef2c0ef006f6c6421ccb

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/1808bcb8681d6716f75f4d4d84876c2982dfd1f7
