### ISSUE TITLE
Empty referer

### ISSUE THREAD

**Issue by Salamander3** [mitchellkrogza/apache-ultimate-bad-bot-blocker#2]
As far as i know there's no valid reason for the referer to be empty unless it's not a real visitor but someone doing something shady. So why no address that too?

**Comment by mitchellkrogza** [comment]
True but have seen some valid sites and some browsers not pass a referer string, seldom but it does happen. I will look into this in more detail over a few days and see if we should put this in.

**Comment by Salamander3** [comment]
Gotcha, maybe as an option disabled by default. 
I wasn't aware of browsers doing that, well whatever you decide it's fine. For what is worth i already do it on my site and traffic is stable, haven't loss any legit visitors for doing it.

**Comment by mitchellkrogza** [comment]
Just did a grep on some logs for empty referers and found the following which I would be hesitant to block because of a blank referer. The google, bing, yahoo and jetmonitor one's all valid IP's.

    Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
    Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)
    Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
    Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)
    SimplePie/1.2 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20090627192103
    Python-urllib/2.7
    libwww-perl/6.05
    jetmon/1.0 (Jetpack Site Uptime Monitor by WordPress.com) 
    Feedly/1.0 (+http://www.feedly.com/fetcher.html; like FeedFetcher-Google)
