### ISSUE TITLE
How to install for cPanel CENTOS 7.3

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/apache-ultimate-bad-bot-blocker#20]
I am still are not understanding that How to install for cPanel CENTOS 7.3, Please let me know the full INSTRUCTIONS. Also if we get any issue with this install then how to uninstall?

**Comment by mitchellkrogza** [comment]
CPanel is turning into a pain, they have taken something as simple as apache and totally messed it up, so much so it's actually embarassing what they have done. I've helped a few people get it working but it seems CPanel just loves to keep overwriting settings. I've not had chance to load CPanel into a Virtual Machine to test what they do but it seems they do NOT like people messing with what they consider a "perfect" system ..... it;s far from from perfect.
