### ISSUE TITLE
[ADD/REMOVE awesome removal]

### ISSUE THREAD

**Issue by Jimmyawesom** [mitchellkrogza/apache-ultimate-bad-bot-blocker#213]
**Is this an Addition / Removal Request?**

**Please List the User-Agent string or Referrer to be added/removed**
example: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/webkit-version (KHTML, like Gecko) Silk/browser-version like Chrome/chrome-version Safari/webkit-version`

**Please explain why it should be added/removed**

**For Additions: Please include a log sample 3-5 lines is adequate**

**Any other important information to consider**

**Comment by Jimmyawesom** [comment]
I have a BOT or BOT‘s or hacker I don’t know all three in my device after my investments and I’ve been battling them since last Thanksgiving a year ago and I’m fed up. I need help.

**Comment by mitchellkrogza** [comment]
Hi @Jimmyawesom you're unfortunately going to need some hands on assistance from someone on the ground with the technical know how to help you. You would need to backup all information and completely wipe your device but you also need to be certain the firmware of your phone hasn't been tampered with either. Sorry I don't have better news but you do need hands on help.

**Comment by Jimmyawesom** [comment]
I know these thing whatever it is stops my it stops me from everything you know it freezes my screen it intercepts my emails my my phone calls it intercepts my phone calls. This thing is crazy it acts like it's like one of my brokers or something. they called places portrayed to be me Whatever it is. It's high tech or a super hacker. It melted my iPhone 11. It melted a demon from the inside out. I am not kidding and I am not crazy.

**Comment by Jimmyawesom** [comment]
I never seen anything like this. It melted a demon in my iPhone 11 from the
inside out as I mean it whatever it is is high tech something that has
never been out there the things I’ve seen it do a human can’t do that so
it’s gotta be I think it’s a hacker and a bot. I don’t know. I’m not good
at this stuffbut thank you for you. Know stopping and trying to help me.
Thank you.

James smith
