### ISSUE TITLE
Dots need to be escaped

### ISSUE THREAD

**Issue by MediaSnog** [mitchellkrogza/apache-ultimate-bad-bot-blocker#22]
This will match any character:
SetEnvIfNoCase Referer "ads.gold" spam_ref=1

So "http://anysite.com/threads/gold-standard-abolished.4534/" will result in a match at "ads/gold".

It should be:
`SetEnvIfNoCase Referer "ads\.gold" spam_ref=1`

**Comment by mitchellkrogza** [comment]
Thanks for the heads up, tested and confirmed. Will be sorted in next Commit.

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/18423a3ece9cde1507a48d9c9639d06886d5b268 thanks @MediaSnog

**Comment by mitchellkrogza** [comment]
@MediaSnog please see latest update in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/issues/27
