### ISSUE TITLE
Apache Failing Reload Suddenly !!!!

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#23]
**Major version change introduced today V2.2017.05**
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/releases/tag/2017-04-19.Build-179

**Requires existence of 3 new include files.**
**PLEASE READ UPDATED INSTRUCTIONS !!!!!**

Apache will fail any auto updates and reloads without the existence of these new include files.

**Comment by srmobile** [comment]
Awesome!!! Looking foreword to trying this out and really appreciate this module, it keeps getting better!! Thanks Mitch!
