### ISSUE TITLE
subscribe my email address to the mailing list

### ISSUE THREAD

**Issue by DarkZeroCD** [mitchellkrogza/apache-ultimate-bad-bot-blocker#24]
Hi,

I sent an empty mail and I then received the mail that invites me by confirming my address.
https://www.world-lolo.com/images/uploads/image.num1492628476.of.world-lolo.com.png
The problem is that I do not receive any confirmations emails  (not in the span either).

Any idea ?

Thx

**Comment by mitchellkrogza** [comment]
The reply should come from google not from world-lolo.com ??

Try again sending a blank message to 

apache-ultimate-bad-bot-blocker+subscribe@googlegroups.com

**Comment by mitchellkrogza** [comment]
https://www.world-lolo.com/images/uploads/image.num1492628476.of.world-lolo.com.png looks very suspicious .... are you sure someone is not spoofing your DNS or you have some malware on your computer?

**Comment by DarkZeroCD** [comment]
https://www.world-lolo.com is an image host and the link I gave is an image :)
At the bottom left of the image, we see that the email has been sent. But I do not get anything.
The email is good, I think rather that it is my mail provider that is not well supported.
I use protonmail.ch which is still used by quite a lot of people.

**Comment by mitchellkrogza** [comment]
Send me your email address to mitchellkrog@gmail.com and I will manually add you
