### ISSUE TITLE
AUBBB Integration with cPanel

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/apache-ultimate-bad-bot-blocker#28]
Apache Ultimate Bad Bot Blocker full integration introduction with cPanel/WHM (CENTOS 7) server.

Step 1:

````
sudo mkdir /etc/apache2/custom.d
cd /etc/apache2/custom.d

sudo wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/globalblacklist.conf -O globalblacklist.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/whitelist-ips.conf -O whitelist-ips.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/whitelist-domains.conf -O whitelist-domains.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/blacklist-ips.conf -O blacklist-ips.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/bad-referrer-words.conf -O bad-referrer-words.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/blacklist-user-agents.conf -O blacklist-user-agents.conf
````

@mitchellkrogza Now I am not understanding Step 6, Where we can add this line in cPanel? 

INCLUDE THE GLOBALBLACKLIST.CONF FILE INTO A VIRTUALHOST

Please let me know that does my installation steps 1 to steps 5 are correct?

**Comment by mitchellkrogza** [comment]
@Nirjonadda  ..... Wherever, you have your vhost config is where you do your insert. I do not have CPanel myself and I am not willing to pay for it either just to be able to support it. So wherever you have your vhost configured in CPanel like this ..... this is where you will do the include

```
<VirtualHost *:80>
DocumentRoot /var/www/mywebsite.com
ServerName mywebsite.com
ErrorLog ${APACHE_LOG_DIR}/mywebsite-error.log
CustomLog ${APACHE_LOG_DIR}/mywebsite-access.log
<Directory "/home/cU5t0m3rH3Lp#42@2/htdocs">
Options +Includes
Options +FollowSymLinks -Indexes
Include /etc/apache2/custom.d/globalblacklist.conf
```

**NOTE: the include MUST be done within the `<Directory>` segment of your vhost config.**

Sorry I cannot be of too much help right now, I just lost my Dad on Friday morning so I am full to the brim with arrangements, shout if you cannot get it right and I will do my best to assist you.

@Nirjonadda you already had this working 3 weeks ago when I first helped you, what has changed now that you no longer have it working ??? Have you switched to Apache now ???
