### ISSUE TITLE
.htaccess method seems to have no useragents in it?

### ISSUE THREAD

**Issue by jonathannz** [mitchellkrogza/apache-ultimate-bad-bot-blocker#29]
Hi there,
Thanks for maintaining this massive list of evil bots and referrers.

I am attempting to use the .htaccess method. It looks to me like the .htaccess file provided includes no blocking of useragents, and instead only has HTTP REFERRERS. Is there a reason for that?

Wouldn't it be wise to also test and block unwanted user agents with .htaccess rewrite rules?

Thanks,

Jonathan

**Comment by mitchellkrogza** [comment]
Hi @jonathannz I will see if I can build that it for you. Spend most of my time on my Nginx Blocker as I don't use Apache anymore myself but still keep this project going and growing for Apache users. Will let you know once I figure out how to include the blocking of User-Agents in the .htaccess

**Comment by mitchellkrogza** [comment]
Have figured it out, now just to rewrite my PHP generator scripts 😁

**Comment by mitchellkrogza** [comment]
@jonathannz please test new .htaccess versions pushed out in commit https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/b6ff45c30b6a4e6afc7009ad586f25bcc6d4e27b please refer back if any issues.

**Comment by jonathannz** [comment]
Thanks Mitchell. I appreciate your swift action on this. I’ll give this .htaccess file a whirl.
Jonathan

**Comment by jonathannz** [comment]
Loaded it, and no issues to report.
Thank you very much.

**Comment by mitchellkrogza** [comment]
Perfect, glad I could help. Make sure to test with some of my curl commands in the README.md to make sure it's working.

**Comment by mitchellkrogza** [comment]
@jonathannz please can you test the following curl commands for me against your site(s) using the .htaccess version. 

I picked up some issues with the regex using exact match with the circumflex `^` reported in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/issues/30 and found a better more accurate regex pattern now integrated into the main globalblacklist file. 

If you can run each of these below against one of your sites and post the output here I would greatly appreciate it, then if needed I will fix the regex pattern in the .htaccess versions of the blocker.

`curl -A "compatible; exabot/1.0" http://www.oneofyoursites.com`

`curl -A "compatible; alexabot/1.0" http://www.oneofyoursites.com`

`curl -A "compatible; GoogleBot/1.0" http://www.oneofyoursites.com`

`curl -A "compatible; Notexabot/1.0" http://www.oneofyoursites.com`

`curl -A "compatible; 360Spider/1.0" http://www.oneofyoursites.com`

`curl -A "compatible; NOT360Spider/1.0" http://www.oneofyoursites.com`
