### ISSUE TITLE
Two errors : Fail2Ban and Apache

### ISSUE THREAD

**Issue by DarkZeroCD** [mitchellkrogza/apache-ultimate-bad-bot-blocker#3]
First error : Fail2ban

```
systemd[1]: Starting LSB: Start/stop fail2ban...
fail2ban[7223]: Starting authentication failure monitor: fail2banWARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
fail2ban[7223]: ERROR  Failed during configuration: Bad value substitution:
fail2ban[7223]: section: [apacherepeatoffender]
fail2ban[7223]: option : action
fail2ban[7223]: key    : port
fail2ban[7223]: rawval : ", protocol="%(protocol)s", chain="%(chain)s"]
fail2ban[7223]: failed!
systemd[1]: Started LSB: Start/stop fail2ban.
```

Second error : Apache

```
apache2[7980]: Reloading web server: apache2 failed!
apache2[7980]: The apache2 configtest failed. Not doing anything. ... (warning).
apache2[7980]: Output of config test was:
apache2[7980]: AH00526: Syntax error on line 4316 of /etc/apache2/custom.d/globalblacklist.conf:
apache2[7980]: order not allowed here
apache2[7980]: Action 'configtest' failed.
apache2[7980]: The Apache error log may have more information.
systemd[1]: apache2.service: control process exited, code=exited status=1
systemd[1]: Reload failed for LSB: Apache2 web server.
```

I'm on Debian with the latest version of Apache and Fail2Ban

An idea ?

**Comment by DarkZeroCD** [comment]
For Apache it's ok.

**Comment by mitchellkrogza** [comment]
Hi DarkZero, did you fix the Apache error? But not the Fail2ban error? I'm out of office but will have a look into this on Saturday. Apologies for the delay. Are you running Apache 2.4 and Fail2ban 0.9.3??

**Comment by DarkZeroCD** [comment]
No problem, it's not urgent :)
For Apache, I put the "Include" in a vhost and not in a directory, for that there was an error. Now it's settled.
For Fail2Ban, I have version 0.8.13-1 (this is the most stable for my distribution), I can put a backport to retrieve a newer version.

For the problem, I think it's due to the fact that it lacks an "action".

**Comment by DarkZeroCD** [comment]
I looked at the issues that existed on your version on nginx. I noticed that version 0.8 did not work with your configuration, so I delete my old configuration and upgraded to version 0.9 and it works very well, no more error.

Now, remains to see the effectiveness.

Thank you for your work ;)

Do you update frequently?

**Comment by mitchellkrogza** [comment]
Great DarkZero, glad you got it working. I do update very frequently, if you look at the commit history you can see how often I update. Having been away for a week there will be a new update tomorrow probably with lots more offenders. Look forward to hearing from you on how it works out for you.

**Comment by mitchellkrogza** [comment]
Pushed out a new commit this morning with about 80 new referers
