### ISSUE TITLE
some bad bot useragents doesn't match due to leading circumflex

### ISSUE THREAD

**Issue by Vorcy1986armyspy** [mitchellkrogza/apache-ultimate-bad-bot-blocker#30]
Some of the bad bot useragents doesn't match the useragent sent from the bots.

For example: 
`BrowserMatchNoCase "^Spbot" bad_bot` would never match the real sent useragent: "Mozilla/5.0 (compatible; spbot/5.0.3; +http://OpenLinkProfiler.org/bot )"
also
`BrowserMatchNoCase "^Netcraft" bad_bot` would never match the real sent useragent "Mozilla/4.0 (compatible; Netcraft Web Server Survey)"

I think its better to remove the leading circumflex "^" in all BrowserMatchNoCase directives to match all these useragents.

**Comment by mitchellkrogza** [comment]
Thanks for the heads up, tested and confirmed. The circumflex was introduced due to false positive matching issue on https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/issues/18

Have found a new regex which seems to sort all of this out, just finalising testing and will release new update shortly for you to test with.

**Comment by mitchellkrogza** [comment]
@Vorcy1986armyspy please try latest release https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/9acbdbde3207c72df466f000bef4d7f5e300e96e using a better regex using word boundaries. Have tested and it seems to be working much better. Please let me know how it goes.

`BrowserMatchNoCase "^(.*?)(\badidxbot\b)(.*)$" good_bot`

`BrowserMatchNoCase "^(.*?)(\bGooglebot\b)(.*)$" good_bot`

`BrowserMatchNoCase "^(.*?)(\b360Spider\b)(.*)$" bad_bot`

**Comment by mitchellkrogza** [comment]
Anyone using the .htaccess versions can you please test to see if same Regex pattern is required on the .htaccess versions of the blocker. Bit strapped for time to test it myself
