### ISSUE TITLE
Delay in Updates

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#31]
Sorry folks due to some scripting changes in progress there are no updates being pushed out. Updates to the blocker should resume by Monday / Tuesday this coming week.

**Comment by DarkZeroCD** [comment]
No problem, thanks to you, it is really impressive the work you do on this script.

Do you have a roadmap?

**Comment by mitchellkrogza** [comment]
Roadmap so far:

1. Make this a self generating repo using Travis CI to do all the generation of files based only on pull requests on the files in _generator_lists. Already have this working 100% on the Nginx Blocker project so that's coming soon.

2. Introduce 2 versions of the blocker for older Apache 2.2 and newer Apache 2.4+ due to mod_access_compat which will be deprecated one day soon. Picked up in this issue https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/issues/32 (testing and investigation in progress)

3. Introduce a config file with switches to enable or disable features. So for instance only check for bad referrers and don't check for user agents / bots. Something simple like a conf file with
```
CHECK_BAD_BOTS=0
CHECK_BAD_REFERRERS=1
WHITELIST_DOMAINS=1
WHITELIST_IPS=1
BLACKLIST_IPS=0

```
......... that's the plan thus far 😄

**Comment by mitchellkrogza** [comment]
@DarkZeroCD Updates have resumed as of today.
Tomorrow I will bring step 1 of the roadmap online.
