### ISSUE TITLE
DEPRECATION of old version - Important Changes

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#37]
Please note the current version in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/tree/master/custom.d **has been deprecated**. 

The existing globalblacklist.conf file in that folder will remain there but will no longer be updated.

**Please refer to the new version specific folders for the blocker at:**

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/tree/master/Apache_2.2

and

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/tree/master/Apache_2.4

Many updates are currently in progress and each Version will have it's own Readme and Configuration Instructions and explanations of the variances between the two versions. 

**For now**, those using the existing original version of the blocker please download the latest updater script from: https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/Apache_2.2/update-apacheblocker.sh

**To make sure you are pulling new updates from the correct location.** 

Your existing update script if not updated will simply continue to work pulling the globalblacklist.conf file from the deprecated folder but it will not include any updates as of today so please make sure you get the latest updater script.

**Comment by DarkZeroCD** [comment]
Thank you for the work done.
How long before version 2 is totally obsolete?
Is it stable the v3?

**Comment by mitchellkrogza** [comment]
No problem and glad it's helping you. Version 2 is deprecated and no longer
being updated. V3 in the Apache_2.2 folder is exactly the same as the old
version just now moved into a different folder. V4 coming in a few weeks
with a lot of mods I have in mind. Have a great day/evening and thanks for
the support.

**Comment by mitchellkrogza** [comment]
Closing, original files now deprecated in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/b82ba8cc7d58c67eae4a521437c25e2dab267a30
