### ISSUE TITLE
Fail2Ban Filter Regex Update (apacherepeatoffender.conf)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#41]
The Custom Jail for Repeat Error 444 and 403 Offenders (filter.d/apacherepeatoffender.conf) has been updated with an improved Regex to catch 444 offenders who had been slipping under the radar, especially the Jorgee Scanner.

This New improved Regex pattern for catching Jorgee and others who may slip past undetected was contributed by Konstantin Goretzki @terriblespider. 

Many Thanks Konstantin.

Pull the updated file as follows:

` sudo https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/_fail2ban_addon/filter.d/apacherepeatoffender.conf -O /etc/fail2ban/filter.d/apacherepeatoffender.conf`

and then

`sudo service fail2ban restart`

Thank you very much @terriblespider

**Comment by DarkZeroCD** [comment]
Done thx ! ;)

**Comment by mitchellkrogza** [comment]
Also check the latest update to https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/Apache_2.2/custom.d/blacklist-ips.conf and https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/Apache_2.4/custom.d/blacklist-ips.conf .... added some new ranges owned by Cyveillance
