### ISSUE TITLE
Receive by mail the IP blocked by Fail2Ban and the reason

### ISSUE THREAD

**Issue by DarkZeroCD** [mitchellkrogza/apache-ultimate-bad-bot-blocker#43]
Hello,
Is it possible to receive by mail the IP blocked by Fail2Ban and the reason of the blocking.

**Comment by mitchellkrogza** [comment]
@DarkZeroCD you can try this

```
[apacherepeatoffender]
enabled = true
logpath = %(apache_access_log)s
filter = apacherepeatoffender
banaction = apacherepeatoffender
action = %(action_mwl)s
bantime  = 86400   ; 1 day
findtime = 604800   ; 1 week
maxretry = 20
```

You should not need to add the `action = %(action_mwl)s` as it should be specified in your jail.local file as the default action. But you can customize each jail this way in Fail2Ban with a different action to perform.

**Comment by DarkZeroCD** [comment]
Does not work.

**Comment by mitchellkrogza** [comment]
@DarkZeroCD mine emails me perfectly but I have my default action specified in the jail.local file much higher up. This is how your jail.local should typically be setup. This is how mine looks (shortened version)

```
# Local Jail.conf File
[INCLUDES]

before = paths-debian.conf

[DEFAULT]

ignoreip = 127.0.0.1/8;
ignorecommand =
bantime  = 600
findtime  = 600
maxretry = 6
backend = auto
usedns = yes
logencoding = auto
enabled = false
filter = %(__name__)s
destemail = me@myemail.com
sender = security@mydomain.com
sendername = Fail2Ban
mta = mail
protocol = tcp
chain = INPUT
port = 0:65535
banaction = iptables-multiport
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mw = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
            %(mta)s-whois[name=%(__name__)s, dest="%(destemail)s", sender="%(sender)s", protocol="%(protocol)s", chain="%(chain)s"]
action_mwl = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", sender="%(sender)s", logpath=%(logpath)s, chain="%(chain)s"]
action_xarf = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             xarf-login-attack[service=%(__name__)s, sender="%(sender)s", logpath=%(logpath)s, port="%(port)s"]
action_cf_mwl = cloudflare[cfuser="%(cfemail)s", cftoken="%(cfapikey)s"]
                %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
action_blocklist_de  = blocklist_de[email="%(sender)s", service=%(filter)s, apikey="%(blocklist_de_apikey)s"]
action_badips = badips.py[category="%(name)s", banaction="%(banaction)s"]

# SET OUR DEFAULT ACTION HERE
# ***************************

action = %(action_mwl)s


# JAILS
# *****

[ssh]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.*
maxretry = 6

[ssh-ddos]
enabled  = true
port     = ssh
filter   = sshd-ddos
logpath  = /var/log/auth.*
maxretry = 6

# OTHER JAILS HERE

[nginxrepeatoffender]
enabled = true
logpath = %(nginx_access_log)s
filter = nginxrepeatoffender
banaction = nginxrepeatoffender
bantime  = 86400   ; 1 day
findtime = 604800   ; 1 week
maxretry = 10
```

**Comment by mitchellkrogza** [comment]
@DarkZeroCD did you get this sorted ??

**Comment by DarkZeroCD** [comment]
its not working on my debian, perhaps, its my configuration :/

**Comment by mitchellkrogza** [comment]
Are you getting any emails from Fail2ban?

**Comment by DarkZeroCD** [comment]
this weekend, I try to solve my problem ;)
I'll keep you informed

**Comment by DarkZeroCD** [comment]
Okay apologies. The mails do not work on my distribution.
What do you use to send mails on your linux?

**Comment by mitchellkrogza** [comment]
Hi @DarkZeroCD you should just try `apt install mailutils`

What is your output of `which mail`

**Comment by DarkZeroCD** [comment]
I did that already.
/usr/bin/mail

Strange, I had never had to configure this part.

**Comment by mitchellkrogza** [comment]
What happens if you run 

mail -s "Test Subject" user@example.com < /dev/null

**Comment by DarkZeroCD** [comment]
mail: Corps du message vide; en espérant que cela soit correct

If I translate
Mail: Message body empty; in the hope that this is correct

*I replaced by my mail

**Comment by mitchellkrogza** [comment]
So it is sending you an email, did you receive it? If so then check your jail.local setting to make sure it has the correct mailer set

**Comment by mitchellkrogza** [comment]
Try Changing the line in jail.local to this

mta = mail

**Comment by DarkZeroCD** [comment]
No I did not receive anything.
But I will not bother you with that. It's not really related to the apache blocker ^^

I will do my research on my side and see what is wrong.

Thank you for your help.

**Comment by mitchellkrogza** [comment]
Check your spam folder  if you are sending to a Gmail address. But try installing mailutils
