### ISSUE TITLE
Missing global.conf

### ISSUE THREAD

**Issue by Tbone542** [mitchellkrogza/apache-ultimate-bad-bot-blocker#44]
Hello,

I am getting a 404 when trying to retrieve the file located at...
https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/globalblacklist.conf

Was this moved or deprecated?

Thanks,
Tbone

**Comment by mitchellkrogza** [comment]
@Tbone542 yes it was deprecated and was documented for about 2 months in Issues before it was actually deprecated. Apologies for this but it had to happen. You need to pull from the Apache_2.2 folder now as that is the same as the existing old version you were pulling.

**Comment by mitchellkrogza** [comment]
So you need to pull from https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/Apache_2.2/custom.d/globalblacklist.conf and also make sure you have all the required include files in the custom.d folder

**Comment by Tbone542** [comment]
Perfect... Thank you.

**Comment by mitchellkrogza** [comment]
No problem apologies for the interruptions
