### ISSUE TITLE
Is space need to be escaped?

### ISSUE THREAD

**Issue by yakusha** [mitchellkrogza/apache-ultimate-bad-bot-blocker#46]
Hi @mitchellkrogza.

I tried to use htaccess version (https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_htaccess_versions/htaccess-mod_rewrite.txt) with apache 2.4.18.

Its throw error. Than I escaped spaces, its work.

Throwed error: RewriteCond %{HTTP_USER_AGENT} ^Mass Downloader.* [NC,OR]
Worked : RewriteCond %{HTTP_USER_AGENT} ^Mass\ Downloader.* [NC,OR]

Am I need to change sometings on htaccess files, or my apache configs?

/sorry for my bad english.
Thans.

**Comment by mitchellkrogza** [comment]
Thanks @yakusha for reporting this I will push out a fix for this in the next update.

**Comment by mitchellkrogza** [comment]
@yakusha after a lot of work I have it fixed now. Please try latest version of .htaccess and let me know. Thanks for reporting this.
