### ISSUE TITLE
Installation on Centos 6, Cpanel V.68

### ISSUE THREAD

**Issue by yakusha** [mitchellkrogza/apache-ultimate-bad-bot-blocker#48]
I used to install same script.

`wget https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/Apache_2.4/install-apacheblocker.sh`

Then I used this path
Service Configuration > Apache Configuration  > Include Editor [Documentation] 

I added this line on Post VirtualHost Include area

```
  <IfModule mod_include.c>
    <Directory "/home/USERDIR/public_html">
	  Include /etc/apache2/custom.d/globalblacklist.conf
    </Directory>
  </IfModule>
```

Then I Restarted.

İts work.

Thanks.
/sorry for my bad english.

**Comment by mitchellkrogza** [comment]
Thanks @yakusha glad you got it working 👍
