### ISSUE TITLE
Access is not blocked for IPs when accessing form Mobile

### ISSUE THREAD

**Issue by pkjoshi** [mitchellkrogza/apache-ultimate-bad-bot-blocker#53]
I have this in my Apache directive which seems to work well while accessing from the desktop PC, but fails when accessing from the Mobile.

The directive is like this:
`<Location "/">
Include /etc/apache2/custom.d/globalblacklist.conf
</Location>
`
and in the included file I have included the ip like

`Require not IP 64.233.173.23/24`

besides When I use the same mobile with USB Tethering it shows altogether a diffrent IP address for example 47.11.195.39 but I have included both ips like 47.11.195.39/24

Apache access logs show the ip in the range 64.233.173.23/24

My question is why the Require Not IP directive is failing when accessing from the Mobile, when It works fine if use the same connection with tethering in Desktop.

Even I have blocked a IP - Require not ip 78.46.81.83/24

but it keep showing in the log like this:
`78.46.81.83 - - [05/Nov/2017:01:55:35 +0530] "POST /xjzgp HTTP/1.1" 200 437 "http://lions322c2.org/xjzgp" "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36"
`
but I can see the same IP being blocked when It is trying to access from desktop

`78.46.81.83 - - [04/Nov/2017:04:05:44 +0530] "POST /vkzhekv HTTP/1.1" 403 632 "http://lions322c2.org/vkzhekv" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)"`

**Comment by mitchellkrogza** [comment]
@pkjoshi Please try the latest updates I found quite a big bug affecting the workings of the whitelisting / blacklisting of IP's.
