### ISSUE TITLE
diffbot

### ISSUE THREAD

**Issue by yakusha** [mitchellkrogza/apache-ultimate-bad-bot-blocker#54]
Hi, I saw some diffbot activity in my access.log

`35.188.153.21 - - [time] "GET / HTTP/1.1" 200 33374 "http://news.google.com/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729; Diffbot/0.1; +http://www.diffbot.com)"`

Its could be bad bot. Its have been listed some networks.

https://www.distilnetworks.com/bot-directory/bot/diffbot/
http://soggi.eu/misc/articles/Diffbot-blocking-bad-bot-rude-content-scraper-from-websites.htm

also, its been our bad referer list. (diffbot.com)

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-referrers.list

**Comment by mitchellkrogza** [comment]
Hi @yakusha sorry for the delay, been sick for the past 10 days but on the mend. Diffbot from my research is an data collecting company who uses this information gathered from web sites to help customers of theirs who pay for their services. Check their web site at https://www.diffbot.com/ generally if I find things like this in my logs and I see it is a paid for service I block them as do I block most SEO companies out there too.

**Comment by mitchellkrogza** [comment]
@yakusha any feedback on this or can I close this issue?

**Comment by yakusha** [comment]
you can close ticket. sorry.

**Comment by mitchellkrogza** [comment]
No worries, closing. All the best for 2018
