### ISSUE TITLE
block all curl, block all wget, block all else?

### ISSUE THREAD

**Issue by treboR-0** [mitchellkrogza/apache-ultimate-bad-bot-blocker#61]
is there a reason you allow wget, curl, and what else i dont know of access?

could you add a tinfoil.conf for people who want to really lock it down?

**Comment by mitchellkrogza** [comment]
@treboR-0 I allow wget and curl to my sites as I have other sites that pull files from them using wget or curl. 

What do you mean by a tinfoil.conf ? 

It's very easy though for me to put those agents into the default custom include file and remove them from the main list which will allow people to choose to enable or disable them.

**Comment by treboR-0** [comment]
By default your system has curl and wget enabled. My service has no reason to allow them for general use. How would I block wget and curl?

**Comment by treboR-0** [comment]
and tinfoil.conf would be a tinfoil hats addition in which you would add a block it all option as you have allowed some bots through that for general purpose probably make sense but in other cases represent an absolute threat. only this list would go wget, curl and whatever else could be used to download content in any form. A bot is a bad bot to some. So whatever else you've left out that isnt chrome/opera/firefox/explorer/safari etc, block it.

**Comment by mitchellkrogza** [comment]
A block all except those specified may cause very unsavory results for a lot of users. Would have to give this some thought and of course test it thoroughly. If you have any ideas send a PR through for it.

With the Nginx blocker it's a relatively simple switch to modify the default from 0 to 1 (as in lines below)  which would block everything except whats been allowed, with Apache the order / access directives will probably have to be modified or some other way ??

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf#L107-L110

**Comment by treboR-0** [comment]
Spelling Error: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf#L171

But default blocker would block all the good bots too? https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf#L128-L165

My goal is block everything except chrome/opera/firefox/explorer/safari and google/bingbot/yandex/duckduck.

My concern is primarily these two most commonly used website piraters curl and wget, which are not marked as 0, I presume marked as blocked, but are not in fact blocked at all. How would I block these, because without them blocked everything here means nothing. Any website can be downloaded relatively quickly via wget.exe or curl.exe.
"~*\bWget/1.15\b"		1;
"~*\bPyCurl\b"		3;

I know stopping these isn't at all common. Or even easy. But I also know it is possible. So let me know when you know, how do I stop these...

**Comment by mitchellkrogza** [comment]
On Nginx `default 0` means allowed. I was just showing an example that if I switched `default 0` to `default 1` it would accomplish it easily on Nginx.

Have you tried over-riding the wget and curl in the `blacklist-user-agents.conf` include file to see what happens? I'm a bit tied up with another project but can try and test it later or re-think this a bit.

**Comment by mitchellkrogza** [comment]
A big problem blocking them in the main list now is a lot of existing users might get very badly affected. A lot of folks use wget and curl in scripts to / from their own servers. So as you say blocking them is not easy as a lot of legit users use them. Thanks for noting typo will send update to fix that.

**Comment by treboR-0** [comment]
Thanks for your ideas:
> Have you tried over-riding the wget and curl in the blacklist-user-agents.conf include file to see what happens
I would need an example of how this could be done. I only write working novel code by accident.

> A big problem blocking them in the main list now is a lot of existing users might get very badly affected.
I am one of those, but would find a work around eventually. Perhaps it could block with IP exceptions, or only block a certain time of day. Security through obscurity can be quite valid.

**Comment by mitchellkrogza** [comment]
@treboR-0 I'll test over-riding them today and get back to you

**Comment by mitchellkrogza** [comment]
@treboR-0 as I suspected when I originally designed the blocker, my custom includes do indeed work as over-rides. You need to modify the blacklist-user-agents.conf file as follows and then restart Apache.

```
# EDIT THIS FILE AS YOU LIKE TO BLACKLIST OR WHITELIST ANY BAD USER-AGENT STRINGS YOU WANT TO SCAN FOR
# ****************************************************************************************************

##############################################################################
#        ___                 __                                              #
#       / _ | ___  ___ _____/ /  ___                                         #
#      / __ |/ _ \/ _ `/ __/ _ \/ -_)                                        #
#     /_/ |_/ .__/\_,_/\__/_//_/\__/                                         #
#        __/_/        __   ___       __     ___  __         __               #
#       / _ )___ ____/ /  / _ )___  / /_   / _ )/ /__  ____/ /_____ ____     #
#      / _  / _ `/ _  /  / _  / _ \/ __/  / _  / / _ \/ __/  '_/ -_) __/     #
#     /____/\_,_/\_,_/  /____/\___/\__/  /____/_/\___/\__/_/\_\\__/_/        #
#                                                                            #
##############################################################################

# Add One Entry Per Line - List all the extra bad User-Agents you want to permanently block or whitelist.

# This is for User-Agents that are not included in the main list of the bot blocker
# This file must exist on your system or Apache will fail a reload due to a missing file
# This allows you finer control of keeping certain bots blocked and automatic updates will
# Never be able to remove this custom list of yours 

# Please note this include file loads first before any of the already whitelisted User-Agents
# in the bad bot blocker. By loading first in line it over-rides anything below it so for instance
# if you want to block Baidu, Google or Bing for any reason you add them to this file which loads
# first and takes precedence over anything below it. This now allows even finer control over the 
# bad bot blocker. Enjoy !!!

# Even though this file is called blacklist-user-agents, as mentioned it can also be used to whitelist user agents
# By adding them below and setting the word bad_bot to good_bot this will permanently whitelist the User-Agent.

# Make sure any words that contain special characters are escaped and include word boundaries as per the Regex examples below.

# Example the User-Agent name "someverybaduseragentname1" is entered as "\bsomeverybaduseragentname1\b"
# Example the User-Agent name "some-very-bad-useragentname2" is entered as "\bsome\-very\-bad\-useragentname1\b" 
# the "\b" are word boundaries which prevents partial matching and false positives.
# Follow the regex formatting examples below.

# ************************
# BLACKLIST ADDITIONAL BOTS
# ************************
BrowserMatchNoCase "^(.*?)(\bwget\b)(.*)$" bad_bot
BrowserMatchNoCase "^(.*?)(\bcurl\b)(.*)$" bad_bot

# ************************
# WHITELIST ADDITONAL BOTS
# ************************
BrowserMatchNoCase "^(.*?)(\bMyVeryGoodUserAgentName\b)(.*)$" good_bot
BrowserMatchNoCase "^(.*?)(\bMy\ Bad\ User\ Agent\b)(.*)$" good_bot
```

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/Apache_2.4/custom.d/blacklist-user-agents.conf#L42-L43

**Comment by mitchellkrogza** [comment]
You can add ANY additional or existing bots in this include file to block or over-ride them.

**Comment by treboR-0** [comment]
Security from all things. Will test real soon. Thanks for your quick help.

**Comment by treboR-0** [comment]
curl 403 Forbidden
wget fails to connect or something very similar to that.

thanks for clarifying the language and location required to do this. 

Of course for someone with my concerns toward friendly bots, for every solution someone will write a new problem. curl and wget are now solved, but, do you now or Could you in the future include in your package a list of "friendly" bots capable of downloading a website? As my dream is to stop everything that isn't a mainstream browser or a search engine and having an up-to-date list of such would be a great start.

**Comment by mitchellkrogza** [comment]
Great so you have nailed keeping wget and curl out `403 Forbidden` is just the response we want. 

Unfortunately yes that is the nature of cybersecurity, as fast as you come up with a solution somebody will be sitting figuring a way around it so its constant work keeping up.

We can certainly start building a list of friendly bots that are able to rip an entire web site, I would make this file an optional include for people so as not to cause any problems for existing users. You are welcome to send any PR's for one's you may find or simple log them here in the Issues system.
