### ISSUE TITLE
/etc/apache2/sites-available/default.conf vs. 000-default.conf

### ISSUE THREAD

**Issue by treboR-0** [mitchellkrogza/apache-ultimate-bad-bot-blocker#62]
Your Apache 2.2 /etc/apache2/sites-available includes a default.conf, my apache 2.4.25 Debian running your 2.2, has a 000-default.conf at that location. Should your default.conf be beside it, instead of it, or renamed as it. Note: the system seems to test out perfectly without it.

**Comment by mitchellkrogza** [comment]
Hi @treboR-0 I do apologize for my late response, I was away having a much needed break. Happy New Year to you.

You can use the 000-default.conf as is, no need to use mine it's only there for an example.
