### ISSUE TITLE
Remove from blocklist

### ISSUE THREAD

**Issue by stevetoza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#63]
Hello, 

I was wondering if you would consider removing the below from the block list

`BrowserMatchNoCase "^(.*?)(\bScreaming\b)(.*)$" bad_bot`

Its causing us issues as we are a digital agency and use screaming frog for our clients for seo purposes 

Thanks

**Comment by raubv0gel** [comment]
@stevetoza Please provide information links. If it’s for SEO and your clients only, it’s okay that Screaming bot is blocked. Such "SEO" companies causes much traffic (costs) on my server – and we don’t profit.

**Comment by stevetoza** [comment]
@raubv0gel - We use screaming frog software for our clients and run it against our servers. As we provide SEO services. We noticed this week when we tried it was getting a 403. When searching the lists I found 

`BrowserMatchNoCase "^(.*?)(\bScreaming\b)(.*)$" bad_bot`

Was blocking the software because the user was Screaming Frog SEO Spider/7.2

**Comment by mitchellkrogza** [comment]
Hi @stevetoza sincere apologies for such a late reply, I've been out of the office for a while due to some family problems. 

Have you tried over-riding it in the blacklist-user-agents.conf file? https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/Apache_2.4/custom.d/blacklist-user-agents.conf

This include file was introduced not only as a blacklist but also as a whitelist and over-ride. Can you try adding 

```BrowserMatchNoCase "^(.*?)(\bScreaming\b)(.*)$" good_bot```

into that file and reload Apache and let me know.

**Comment by stevetoza** [comment]
Hi @mitchellkrogza, 

No worries totally understand, just tried adding that into blacklist-user-agents.conf restarted apache and still getting a 403 when trying to use Screaming Frog on the site

**Comment by mitchellkrogza** [comment]
Hi @stevetoza thanks for testing, let me see what I can figure out to get the over-ride working properly.

**Comment by stevetoza** [comment]
@mitchellkrogza - Could you remove it from the bad list for now, until you work out why the whitelist doesnt work? Would really help a lot 👍

**Comment by mitchellkrogza** [comment]
@stevetoza I found some bugs affecting certain things which is all fixed now.
I have tested today with the following modification to `blacklist-user-agents.conf` which can be used for both black and whitelisting. The change below allows Screaming through successfully.

```
# Add One Entry Per Line - List all the extra bad User-Agents you want to permanently block
# This is for User-Agents that are not included in the main list of the bot blocker
# This allows you finer control of keeping certain bots blocked and automatic updates will
# Never be able to remove this custom list of yours 

#BrowserMatchNoCase "^wget" bad_bot=1
#BrowserMatchNoCase "^curl" bad_bot=1
#BrowserMatchNoCase "^(.*?)(\bwget\b)(.*)$" bad_bot
BrowserMatchNoCase "^(.*?)(\bScreaming\b)(.*)$" good_bot
```
