### ISSUE TITLE
Low performance if many Virtual Hosts

### ISSUE THREAD

**Issue by raubv0gel** [mitchellkrogza/apache-ultimate-bad-bot-blocker#64]
We have many domains and therefore Virtual Hosts. We have `Include /etc/apache2/custom.d/globalblacklist.conf` about 16 times (in each root doc of each Virtual Host). `service apache2 reload` needs many seconds to load. For the moment I can’t say if doing a http(s)-request has lower performance too – I will test.

Is there any possibility to include the `globalblacklist.conf` globally, i. e. for all hosts? I think otherwise (like above) Apache2 is creating many data structures internally because there are many copies of the rules (each include creates a copy). After my research I could not find a possibility to do it globally in Apache2 (2.4.7).

**Comment by raubv0gel** [comment]
Ok, a page like [https://prosodia.de/voe/](url) seems to be loaded in about 0.4 s more (testes with Firefox debug tools) if `globalblacklist.conf` is included.

**Comment by mitchellkrogza** [comment]
Hi @raubv0gel the globalblacklist.conf should ideally be loaded only once by Apache and it will  automatically be available to all sites. Loading it into memory multiple times adds serious overhead and you will run into major performance problems. I have tested all my sites with the blocker on and off and there is performance knocks that I have ever noticed.

**Comment by raubv0gel** [comment]
Yes, this would be nice, but how to do this? How to globally include only once? In your example you include it in `<Directory>` in a single `<VirtualHost>`. I have no idea how to include for all Virtual Hosts. A global  `<Location />` (outside a `<VirtualHost>`) seems not to work. Do have a working example for me and maybe for your docs?

**Comment by mitchellkrogza** [comment]
Sorry @raubv0gel  my apologies I got totally confused between this and my Nginx blocker. I'll have to look into this as unfortunately the multiple loading right now is the only way. I'll see if a global way can be figured out.

**Comment by raubv0gel** [comment]
NP! I will do some more research to find a solution. It would be really sad if Apache2 does’t provide a way to do this. If I find a solution, I will post it here.

**Comment by raubv0gel** [comment]
This should be a safe solution (place after VirtualHosts configuration):

```apache
# ######################################
# GLOBAL! deny bad bots and IP addresses
# ######################################
#
# should be set after <VirtualHost>s; see https://httpd.apache.org/docs/2.4/sections.html#merging
<Location "/">
	# When authorization is enabled, it is normally inherited by each subsequent configuration section, unless a different set of authorization directives is specified. This is the default action, which corresponds to an explicit setting of AuthMerging Off.
	# However, there may be circumstances in which it is desirable for a configuration section's authorization to be combined with that of its predecessor while configuration sections are being merged. Two options are available for this case, And and Or.
	# When a configuration section contains AuthMerging And or AuthMerging Or, its authorization logic is combined with that of the nearest predecessor (according to the overall order of configuration sections) which also contains authorization logic as if the two sections were jointly contained within a <RequireAll> or <RequireAny> directive, respectively.
	AuthMerging And
	# include black list
	Include /etc/apache2/custom.d/globalblacklist.conf
</Location>
```

**Comment by mitchellkrogza** [comment]
Thanks so much @raubv0gel for figuring this out. I have merged your PR and thank you so much for the contribution.

**Comment by raubv0gel** [comment]
Thank you too :-)
