### ISSUE TITLE
Fix paths in README.md

### ISSUE THREAD

**Issue by raubv0gel** [mitchellkrogza/apache-ultimate-bad-bot-blocker#65]
There are several dead links (404) in README.md like https://raw.githubusercontent.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/master/custom.d/whitelist-ips.conf They should be fixed.

**Comment by mitchellkrogza** [comment]
Thanks @raubv0gel I had started updating the Readme last year to reflect the changes with the introduction of two separate version 2.2 and 2.4 and that left all those dead links. I will get to updating the whole Readme properly tomorrow. Thanks again ;)

**Comment by raubv0gel** [comment]
Thank you too! If you need some help, please let me know ;-)
