### ISSUE TITLE
unblock mail.ru bot

### ISSUE THREAD

**Issue by max-krueper** [mitchellkrogza/apache-ultimate-bad-bot-blocker#67]
I wonder why mail.ru is blocked. It's one of the biggest mail and search providers and social networks in russia.

**Comment by mitchellkrogza** [comment]
Hi @max-krueper it's was originally blocked as an incoming referrer as a lot of referrer spam emanated from that domain. Will review it's removal.

**Comment by thezoggy** [comment]
looking through my logs, I do see:
```
localhost:80 217.69.143.69 - - [29/Dec/2017:23:47:54 +0000] "GET /robots.txt HTTP/1.0" 200 271 "-" "Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/Robots/2.0; +http://go.mail.ru/help/robots)"
```

so instead of mail.ru perhaps to target just the bot we do `Mail.RU_Bot` ?
