### ISSUE TITLE
RequireAny not allowed here

### ISSUE THREAD

**Issue by hostingfuze** [mitchellkrogza/apache-ultimate-bad-bot-blocker#68]
AH00526: Syntax error on line 7024 of /etc/apache2/custom.d/globalblacklist.conf:
<RequireAny not allowed here

apache2 -v
Server version: Apache/2.4.25 (Debian)

<VirtualHost *:443>
DocumentRoot /var/www/html
Include /etc/apache2/custom.d/globalblacklist.conf
ServerName ...
#DirectoryIndex index index.php index.html
SSLEngine on
SSLCertificateFile /key/ssl-....crt
SSLCertificateKeyFile /key/ssl-....key
RewriteEngine On
ServerSignature Off
#CustomLog /var/log/apache/...-access.log combined
ErrorLog /var/log/apache2/...-error.log
</VirtualHost>

**Comment by mitchellkrogza** [comment]
Hi @hostingfuze are you using the Apache 2.2 or 2.4 version of the blocker?

**Comment by hostingfuze** [comment]
@mitchellkrogza ,
I have specified this 

apache2 -v
Server version: Apache/2.4.25 (Debian)

thanks in advance,

**Comment by mitchellkrogza** [comment]
@hostingfuze do you have the module access_compat installed? Please check with `apache2ctl -M`

```
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
```

**Comment by hostingfuze** [comment]
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 brotli_module (shared)
 cache_module (shared)
 cgi_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 http2_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 ratelimit_module (shared)
 remoteip_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)

**Comment by mitchellkrogza** [comment]
@hostingfuze I see you have the blocker include in the wrong place, please pay attention to step 6 of the instructions > https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker
