### ISSUE TITLE
Client IP Beeing blocked

### ISSUE THREAD

**Issue by dmariaa** [mitchellkrogza/apache-ultimate-bad-bot-blocker#7]
We have seen that in some of your latest versions you have included private networks in the banned ip lists:

deny from 172.16.0.0/12

We have included this network in our whitelist-ips.conf as:

Allow from 172.16.0.0/12

Config checked up, apache restarted.... we are getting lots of:

[access_compat:error] [pid 5755] [client 172.31.41.192:63495] AH01797: client denied by server configuration:

Shouldn't it be allowing requests from that IP?

Apache version:

Server version: Apache/2.4.25 (Amazon)
Server built:   Jan 19 2017 16:55:49

Kind regards

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/c76e72174f2b6f7b3586394c8bfd4dca612acdb3 have left the 10.0.0.0 range blocked as that should never be publicly routable. Let me know if you have any more problems.

**Comment by mitchellkrogza** [comment]
Have also removed 10.0.0.0/8 and 192.168.0.0/16 as per an issue logged by another issue. Not a good idea blocking these due to some people internal network structures. Removed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/6fee28468ac8baf265b79e05c1afc9cf90f90d25

**Comment by dmariaa** [comment]
The most problematic thing for us it's that whitelisting the IP didn't work, is this a known issue?

Thanks for your good work and kind regards

**Comment by mitchellkrogza** [comment]
Yes the blacklisted IP's seem to override what is whitelisted, need to have a look at some changes in the logic there. Will figure something out.

**Comment by mitchellkrogza** [comment]
Also a reason I have always been very careful what is blacklisted in the IP blocks in the first place. Didn't give full though to blocking the private IANA network range blocks as they are used by many companies for internal routing.

**Comment by dmariaa** [comment]
Yes, can be the problem on whitelisting due to the mixing of pre and post 2.4 authorization directives? It seems that mixing old and new directives is discouraged as it can not work as expected? see https://httpd.apache.org/docs/2.4/upgrading.html

Maybe a solution would be upgrade to the new 2.4+ directives? I will make some tests to check and let you know...

**Comment by mitchellkrogza** [comment]
Please report back on that. Actually considering doing the blacklisted IP address ranges as an include file that users can control themselves. Just like the whitelist-ips.conf and whitelist-domains.conf .... this gives users FULL control over what they do and do not want to block. Remember I might have an aggressive IP attacking my servers but other people might not want to have that IP blacklisted.
