### ISSUE TITLE
Qwantify should not be a bad bot 

### ISSUE THREAD

**Issue by eldk** [mitchellkrogza/apache-ultimate-bad-bot-blocker#72]
Hello,

Quantify is not a bad bot.

I have whitelisted it in blacklist-user-agents.conf : 
```
BrowserMatchNoCase "^(.*?)(\bQwantify\b)(.*)$" good_bot
```
https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/30cc04286fbd4758b3117e4748acd2ba5908ddf4/Apache_2.4/custom.d/globalblacklist.conf#L487

https://about.qwant.com/

https://udger.com/resources/ua-list/bot-detail?bot=Qwantify

Thanks,

Eric

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/7aab4d262bfe59fdbf4e8ba767828eaadbcdc05f

**Comment by eldk** [comment]
Thanks.

**Comment by skswales** [comment]
Hmm. Qwantify certainly behaves like a bad bot. It does not respect robots.txt

**Comment by mitchellkrogza** [comment]
Thanks @skswales will re-review this.

**Comment by mitchellkrogza** [comment]
@skswales 

```194.187.x.x - - [03/May/2018:21:43:22 +0200] "GET /robots.txt HTTP/1.1" 301 178 "-" "Mozilla/5.0 (compatible; Qwantify/2.4w; +https://www.qwant.com/)/2.4w"```

**Comment by mitchellkrogza** [comment]
Ok @skswales many thanks for the clarity, will re-add on next build, Qwant can be removed again one day if they obey robots.txt, users can of course always whitelist it manually.

**Comment by skswales** [comment]
Thanks. It also doesn't help that there is seemingly no webmaster or robots information on their site.

**Comment by eldk** [comment]
Hello,

I've send them a message to alert on the problem.

Some others allowed bot don't respect at all robots.txt : Googlebot, for example should index some page thus they are not allowed through robots.txt. You are now aware of this by mail  from GSC .

Waiting their response ...

Thanks,

Eric

**Comment by mitchellkrogza** [comment]
Thanks @eldk
