### ISSUE TITLE
Doesn't work on HTTPS?

### ISSUE THREAD

**Issue by OlafV83** [mitchellkrogza/apache-ultimate-bad-bot-blocker#78]
The blocklist works on all websites when HTTP is used, but doesn't work with the HTTPS VHOSTS.
Am I doing something wrong? The <VirtualHost *:80> & <VirtualHost *:443> are the same.
The <VirtualHost *:443> is configured as follow:

<Directory /var/www/<domain>/web>
                                # Clear PHP settings of this website
                                <FilesMatch ".+\.ph(p[345]?|t|tml)$">
                                                SetHandler None
                                </FilesMatch>
                                Options +FollowSymLinks
                                Include /etc/apache2/custom.d/globalblacklist.conf
                                AllowOverride All
                                                                Require all denied

This is a Ubuntu 16.04 server with Apache/2.4.18.

**Comment by mitchellkrogza** [comment]
Hi @OlafV83 excuse my late reply to this. What version of the blocker are you using? 2.2 or 2.4 ?
