### ISSUE TITLE
Apache 2.2.15

### ISSUE THREAD

**Issue by stevetoza** [mitchellkrogza/apache-ultimate-bad-bot-blocker#8]
Hello, 

I was wondering if this has been tested on Apache 2.2? If not I was going to give it a try. To include this globally in apache could the include just be added to httpd.conf?

Thanks
Steve

**Comment by mitchellkrogza** [comment]
Not tested on 2.2 but you can try. Not sure if:
BrowserMatchNoCase
SetEnvIfNoCase Referer

are supported on 2.2 ?? just check Apache docs but try it out nonetheless you will quickly find out if it works or not. Please report back with any errors and if so I will consider pushing out a specific version for 2.2

**Comment by mitchellkrogza** [comment]
To answer your question, yes use the same configuration instructions as per 2.4

**Comment by stevetoza** [comment]
Hello, 

Checked and 

BrowserMatchNoCase
SetEnvIfNoCase Referer

Is compatible, when trying to include the globalblacklist file in httpd.conf so that its globally active i'm getting 

`Starting httpd: Syntax error on line 4398 of /etc/httpd/custom.d/globalblacklist.conf:
order not allowed here`

**Comment by mitchellkrogza** [comment]
So it's failing on "Order Allow,Deny"

Apache changed that from 2.2 when they went to 2.4. The allow directives changed syntax.

What Distro are you using so I can test it out on same distro as you and see if adaptations can be made for Apache 2.2.

**Comment by stevetoza** [comment]
Many thanks, 

Using CentOS 6.8, Apache version Apache/2.2.15 as this is CentOS could a version be made so the include files land in /etc/httpd also. 

If you need a VPS to test this on let me know i'm more than happy to provide one.

**Comment by mitchellkrogza** [comment]
Let me set up a test VM with CentOS 6.8 and see if I can find a workaround for Apache 2.2

**Comment by mitchellkrogza** [comment]
Just another note ... the error you got "order not allowed here" is because you did not do the include within a <Directory></Directory> section of the Virtualhost.

```
    <Directory "/var/www/html/centos">
    Include /etc/httpd/conf/conf.d/globalblacklist.conf
    </Directory>
```

**Comment by stevetoza** [comment]
Hello, 

I see - Will give it a test later on and thanks for the CentOS version 👍

**Comment by mitchellkrogza** [comment]
Introduced in https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/commit/7c27b4eb68254aaff59ef7e0f203420cc13d26eb
